 {"2-Tel B.V","TTL"},
 {"3Com Corporation","TCM"},
 {"3D Perception","TDP"},
 {"3M","VSD"},
 {"3NOD Digital Technology Co. Ltd.","NOD"},
 {"A D S Exports","NGS"},
 {"A Plus Info Corporation","API"},
 {"A&amp;R Cambridge Ltd.","ACG"},
 {"A/Vaux Electronics","AVX"},
 {"A+V Link","APV"},
 {"Aashima Technology B.V.","TRU"},
 {"Aava Mobile Oy","AAM"},
 {"ABBAHOME INC.","ABA"},
 {"Abeam Tech Ltd.","MEG"},
 {"Ably-Tech Corporation","ATC"},
 {"AboCom System Inc.","ABC"},
 {"ACC Microelectronics","WTC"},
 {"Access Works Comm Inc","AWC"},
 {"Acco UK Ltd.","PKA"},
 {"Accton Technology Corporation","ACC"},
 {"Acculogic","ACU"},
 {"AccuScene Corporation Ltd","ASL"},
 {"Ace CAD Enterprise Company Ltd","ANT"},
 {"Acer Inc","CHE"},
 {"Acer Labs","ALI"},
 {"Acer Netxus Inc","ANX"},
 {"Acer Technologies","ACR"},
 {"Acksys","ACK"},
 {"Acnhor Datacomm","ADC"},
 {"Acon","CAL"},
 {"Acrolink Inc","ALK"},
 {"Acroloop Motion Control Systems Inc","ACM"},
 {"ACT Labs Ltd","LAB"},
 {"Actek Engineering Pty Ltd","ACE"},
 {"Actiontec Electric Inc","AEI"},
 {"ActivCard S.A","ACV"},
 {"Aculab Ltd","ACB"},
 {"Acutec Ltd.","ALM"},
 {"AD electronics","GLE"},
 {"Ad Lib MultiMedia Inc","ADM"},
 {"Adaptec Inc","ADP"},
 {"Adax Inc","ADX"},
 {"ADC-Centre","RSH"},
 {"Add Value Enterpises (Asia) Pte Ltd","AVE"},
 {"Addi-Data GmbH","ADA"},
 {"ADI Systems Inc","ADI"},
 {"ADPM Synthesis sas","DPM"},
 {"Adrienne Electronics Corporation","AXB"},
 {"Adtek","ADT"},
 {"Adtek System Science Company Ltd","ADK"},
 {"ADTI Media, Inc","FLE"},
 {"Adtran Inc","AND"},
 {"Advan Int&#039;l Corporation","AGM"},
 {"Advance Computer Corporation","AVN"},
 {"Advanced Digital Systems","MSM"},
 {"Advanced Electronic Designs, Inc.","AED"},
 {"Advanced Engineering","RJS"},
 {"Advanced Gravis","GRV"},
 {"Advanced Integ. Research Inc","AIR"},
 {"Advanced Logic","ALR"},
 {"Advanced Micro Devices Inc","ADV"},
 {"Advanced Micro Peripherals Ltd","EVE"},
 {"Advanced Optics Electronics, Inc.","AOE"},
 {"Advanced Peripheral Devices Inc","ADD"},
 {"Advanced Research Technology","ABV"},
 {"Advanced Signal Processing Technologies","PSA"},
 {"Advantech Co., Ltd.","AHC"},
 {"Aerodata Holdings Ltd","ADH"},
 {"Aetas Peripheral International","AEP"},
 {"Aethra Telecomunicazioni S.r.l.","AET"},
 {"Agentur Chairos","CHS"},
 {"Agilent Technologies","AGT"},
 {"Ahead Systems","ASI"},
 {"AIMS Lab Inc","AIM"},
 {"Airlib, Inc","AYR"},
 {"Aironet Wireless Communications, Inc","AWL"},
 {"Aiwa Company Ltd","AIW"},
 {"AJA Video Systems, Inc.","AJA"},
 {"AKAMI Electric Co.,Ltd","AKE"},
 {"Akebia Ltd","AKB"},
 {"AKIA Corporation","AKI"},
 {"AL Systems","ALH"},
 {"Alacron Inc","ALA"},
 {"Alana Technologies","ALN"},
 {"Alcatel","AOT"},
 {"Alcatel Bell","ABE"},
 {"Aldebbaron","ADB"},
 {"Alenco BV","ALE"},
 {"ALEXON Co.,Ltd.","ALX"},
 {"Alfa Inc","AFA"},
 {"Algolith Inc.","ALO"},
 {"AlgolTek, Inc.","AGO"},
 {"Alien Internet Services","AIS"},
 {"Allen Bradley Company","ABD"},
 {"Alliance Semiconductor Corporation","ALL"},
 {"Allied Telesis KK","ATI"},
 {"Allied Telesyn International (Asia) Pte Ltd","ATA"},
 {"Allied Telesyn Int&#039;l","ATK"},
 {"Allion Computer Inc.","ACO"},
 {"Alpha Data","XAD"},
 {"Alpha Telecom Inc","ATD"},
 {"Alpha-Top Corporation","ATP"},
 {"AlphaView LCD","ALV"},
 {"ALPS ALPINE CO., LTD.","APE"},
 {"ALPS ALPINE CO., LTD.","ALP"},
 {"ALPS ALPINE CO., LTD.","AUI"},
 {"Alta Research Corporation","ARC"},
 {"Altec Corporation","ALC"},
 {"Altec Lansing","ALJ"},
 {"ALTINEX, INC.","AIX"},
 {"Altmann Industrieelektronik","AIE"},
 {"Altos Computer Systems","ACS"},
 {"Altos India Ltd","AIL"},
 {"Alvedon Computers Ltd","CNC"},
 {"Ambient Technologies, Inc.","AMB"},
 {"Altra","ALT"},
 {"Amdek Corporation","AMD"},
 {"America OnLine","AOL"},
 {"American Biometric Company","YOW"},
 {"American Express","AXP"},
 {"American Magnetics","AXI"},
 {"American Megatrends Inc","AMI"},
 {"American Nuclear Systems Inc","MCA"},
 {"American Power Conversion","CNB"},
 {"American Power Conversion","APC"},
 {"Amimon LTD.","AMN"},
 {"Amino Technologies PLC and Amino Communications Limited","AMO"},
 {"AMiT Ltd","AKL"},
 {"AMP Inc","AMP"},
 {"Amptron International Inc.","AII"},
 {"AMT International Industry","AMT"},
 {"AmTRAN Technology Co., Ltd.","AMR"},
 {"AMX LLC","AMX"},
 {"Anakron","ANA"},
 {"Analog &amp; Digital Devices Tel. Inc","ADN"},
 {"Analog Devices Inc","ADS"},
 {"Analog Way SAS","ANW"},
 {"Analogix Semiconductor, Inc","ANL"},
 {"Anchor Bay Technologies, Inc.","ABT"},
 {"Anatek Electronics Inc.","AAE"},
 {"Ancor Communications Inc","ACI"},
 {"Ancot","ANC"},
 {"Anderson Multimedia Communications (HK) Limited","AML"},
 {"Andrew Network Production","ANP"},
 {"Anigma Inc","ANI"},
 {"Anko Electronic Company Ltd","ANK"},
 {"Ann Arbor Technologies","AAT"},
 {"an-najah university","BBB"},
 {"Anorad Corporation","ANO"},
 {"ANR Ltd","ANR"},
 {"Ansel Communication Company","ANS"},
 {"Antex Electronics Corporation","AEC"},
 {"AOpen Inc.","AOA"},
 {"AP Designs Ltd","APX"},
 {"Apache Micro Peripherals Inc","DNG"},
 {"Aplicom Oy","APL"},
 {"Appian Tech Inc","APN"},
 {"Apple Computer Inc","APP"},
 {"AppliAdata","APD"},
 {"Applied Creative Technology","ACT"},
 {"Applied Memory Tech","APM"},
 {"Apricot Computers","ACL"},
 {"Aprilia s.p.a.","APR"},
 {"ArchiTek Corporation","ATJ"},
 {"Archtek Telecom Corporation","ACH"},
 {"Arcus Technology Ltd","ATL"},
 {"AREC Inc.","ARD"},
 {"Arescom Inc","ARS"},
 {"Argolis","AGL"},
 {"Argosy Research Inc","ARI"},
 {"Argus Electronics Co., LTD","ARG"},
 {"Ariel Corporation","ACA"},
 {"Arima","ARM"},
 {"Arithmos, Inc.","ADE"},
 {"Ark Logic Inc","ARK"},
 {"Arlotto Comnet Inc","ARL"},
 {"ARMSTEL, Inc.","AMS "},
 {"Arnos Insturments &amp; Computer Systems","AIC"},
 {"ARRIS Group, Inc. ","ARR"},
 {"ART s.r.l.","IMB"},
 {"Artish Graphics Inc","AGI"},
 {"Arvanics","NPA"},
 {"Asahi Kasei Microsystems Company Ltd","AKM"},
 {"Asante Tech Inc","ASN"},
 {"Ascom Business Systems","HER"},
 {"Ascom Strategic Technology Unit","ASC"},
 {"ASEM S.p.A.","ASM"},
 {"ASEM S.p.A.","AEM"},
 {"AseV Display Labs","ASE"},
 {"Ashton Bentley Concepts","ASH"},
 {"Asia Microelectronic Development Inc","AMA"},
 {"Ask A/S","ASK"},
 {"Askey Computer Corporation","DYN"},
 {"ASP Microelectronics Ltd","ASP"},
 {"Askey Computer Corporation","AKY"},
 {"Aspen Tech Inc","ACP"},
 {"AST Research Inc","AST"},
 {"Astec Inc","JAC"},
 {"ASTRA Security Products Ltd","ADL"},
 {"ASTRO DESIGN, INC.","ATO"},
 {"Asuscom Network Inc","ASU"},
 {"AT&amp;T","ATT"},
 {"AT&amp;T Global Info Solutions","GIS"},
 {"AT&amp;T Microelectronics","HSM"},
 {"AT&amp;T Microelectronics","TME"},
 {"AT&amp;T Paradyne","PDN"},
 {"Atelier Vision Corporation","AVJ"},
 {"Athena Informatica S.R.L.","ATH"},
 {"Athena Smartcard Solutions Ltd.","ATN"},
 {"Athenix Corporation","ATX"},
 {"ATI Tech Inc","BUJ"},
 {"Atlantis","CFG"},
 {"ATM Ltd","ATM"},
 {"Atom Komplex Prylad","AKP"},
 {"Attachmate Corporation","AMC"},
 {"Attero Tech, LLC","FWA"},
 {"Audio Processing Technology  Ltd","APT"},
 {"AudioScience","ASX"},
 {"August Home, Inc.","AUG"},
 {"Auravision Corporation","AVC"},
 {"Aureal Semiconductor","AUR"},
 {"Autologic Inc","APS"},
 {"automated computer control systems","CLT"},
 {"Autotime Corporation","AUT"},
 {"Auvidea GmbH","AUV"},
 {"Avalue Technology Inc.","AVL"},
 {"Avance Logic Inc","ALS"},
 {"Avaya Communication","AVA"},
 {"Avencall","AEN"},
 {"AVer Information Inc.","AVR"},
 {"Avid Electronics Corporation","AVD"},
 {"AVM GmbH","AVM"},
 {"Avolites Ltd","AAA"},
 {"Avocent Corporation","AVO"},
 {"Avtek (Electronics) Pty Ltd","AVT"},
 {"AWETA BV","ACD"},
 {"Axel","AXL"},
 {"AXIOMTEK CO., LTD.","AXC"},
 {"Axonic Labs LLC","AXO"},
 {"Axtend Technologies Inc","AXT"},
 {"Axxon Computer Corporation","AXX"},
 {"AXYZ Automation Services, Inc","AXY"},
 {"Aydin Displays","AYD"},
 {"AZ Middelheim - Radiotherapy","AZM"},
 {"Aztech Systems Ltd","AZT"},
 {"B&amp;Bh","BBH"},
 {"B.&amp; V. s.r.l.","SMR"},
 {"B.F. Engineering Corporation","BFE"},
 {"B.U.G., Inc.","BUG"},
 {"Bang &amp; Olufsen","BNO"},
 {"Banksia Tech Pty Ltd","BNK"},
 {"Banyan","BAN"},
 {"BARC","BRC"},
 {"Barco Display Systems","BDS"},
 {"Barco GmbH","BCD"},
 {"Barco Graphics N.V","BGB"},
 {"Barco, N.V.","BPS"},
 {"Barco, N.V.","DDS"},
 {"Baug &amp; Olufsen","BEO"},
 {"Beaver Computer Corporaton","BCC"},
 {"Beckhoff Automation","BEC"},
 {"Beckworth Enterprises Inc","BEI"},
 {"Beijing Aerospace Golden Card Electronic Engineering Co.,Ltd.","AGC"},
 {"Beijing AnHeng SecoTech Information Technology Co., Ltd.","AHS"},
 {"Beijing ANTVR Technology Co., Ltd.","ANV"},
 {"Beijing Northern Radiantelecom Co.","NRT"},
 {"Beko Elektronik A.S.","BEK"},
 {"Beltronic Industrieelektronik GmbH","BEL"},
 {"Benson Medical Instruments Company","BMI"},
 {"B&amp;R Industrial Automation GmbH","BUR"},
 {"Best Buy","INZ"},
 {"Best Buy","VPR"},
 {"Best Power","BPU"},
 {"Biamp Systems Corporation","BIA"},
 {"BICC Data Networks Ltd","ICC"},
 {"Big Island Communications","BIC"},
 {"Billion Electric Company Ltd","BIL"},
 {"BioLink Technologies","BLN"},
 {"BioLink Technologies International, Inc.","BIO"},
 {"BIOMED Lab","BML"},
 {"Biomedical Systems Laboratory","BSL"},
 {"BIOMEDISYS","BMS"},
 {"Biometric Access Corporation","BAC"},
 {"BioTao Ltd","BTO"},
 {"Bit 3 Computer","BIT"},
 {"Bit 3 Computer","BTC"},
 {"Bitfield Oy","BTF"},
 {"BitHeadz, Inc.","BHZ"},
 {"Bitworks Inc.","BWK"},
 {"Blackmagic Design","BMD"},
 {"Blonder Tongue Labs, Inc.","BDR"},
 {"Bloomberg L.P.","BLP"},
 {"Boca Research Inc","ZZZ"},
 {"Boca Research Inc","BRI"},
 {"BodySound Technologies, Inc.","BST"},
 {"Boeckeler Instruments Inc","BII"},
 {"Booria CAD/CAM systems","BCS"},
 {"BOS","BOS"},
 {"Bose Corporation","BSE"},
 {"Boulder Nonlinear Systems","BNS"},
 {"Braemac Pty Ltd","BRA"},
 {"Braemar Inc","BRM"},
 {"Brahler ICS","BDO"},
 {"Brain Boxes Limited","BBL"},
 {"Bridge Information Co., Ltd","BRG"},
 {"BRIGHTSIGN, LLC","BSN"},
 {"Brilliant Technology","BTE"},
 {"Broadata Communications Inc. ","BCI"},
 {"Broadcom","BCM"},
 {"BROTHER INDUSTRIES,LTD.","BRO"},
 {"BTC Korea Co., Ltd","NFC"},
 {"Budzetron Inc","BGT"},
 {"Bull","BUL"},
 {"Bull AB","BNE"},
 {"Busicom","BLI"},
 {"BusTech Inc","BTI"},
 {"BusTek","BUS"},
 {"Butterfly Communications","FLY"},
 {"Buxco Electronics","BXE"},
 {"byd:sign corporation","BYD"},
 {"C3PO S.L.","XMM"},
 {"CA &amp; F Elettronica","CAC"},
 {"Cabletime Ltd","CBT"},
 {"Cabletron System Inc","CSI"},
 {"Cache","CCI"},
 {"CalComp","CAG"},
 {"CalComp","CDP"},
 {"Calibre UK Ltd","CUK"},
 {"California Institute of Technology","CSO"},
 {"Cambridge Audio","CAM"},
 {"Cambridge Electronic Design Ltd","CED"},
 {"Cambridge Research Systems Ltd","CMR"},
 {"Canon Inc","CNN"},
 {"Canon Inc.","CAI"},
 {"Canonical Ltd.","UBU"},
 {"Canopus Company Ltd","CAN"},
 {"Capella Microsystems Inc.","CPM"},
 {"Capetronic USA Inc","CCP"},
 {"Capstone Visua lProduct Development ","DJE"},
 {"Cardinal Company Ltd","CAR"},
 {"Cardinal Technical Inc","CRD"},
 {"CardLogix","CLX"},
 {"Carina System Co., Ltd.","CKJ"},
 {"Carl Zeiss AG","CZE"},
 {"CASIO COMPUTER CO.,LTD","CAS"},
 {"Castles Automation Co., Ltd","CAA"},
 {"Cavium Networks, Inc","CAV"},
 {"C-C-C Group Plc","FVX"},
 {"CCL/ITRI","CCL"},
 {"C-Cube Microsystems","CCC"},
 {"C-DAC","CEP"},
 {"Cebra Tech A/S","CBR"},
 {"Cefar Digital Vision","CEF"},
 {"Centurion Technologies P/L","CEN"},
 {"Century Corporation","TCE"},
 {"Cerevo Inc.","CRV"},
 {"Ceronix","CER"},
 {"Ceton Corporation","TOM"},
 {"CH Products","CHP"},
 {"ChangHong Electric Co.,Ltd","CHD"},
 {"Chase Research PLC","CHA"},
 {"Cherry GmbH","CHY"},
 {"Chi Mei Optoelectronics corp.","CMO"},
 {"CHIC TECHNOLOGY CORP.","CHM"},
 {"Chicony Electronics Company Ltd","CEC"},
 {"Chimei Innolux Corporation","CMN"},
 {"China Hualu Group Co., Ltd.","HLG"},
 {"Chloride-R&amp;D","CHL"},
 {"Christie Digital Systems Inc","CDG"},
 {"Chromatec Video Products Ltd","CVP"},
 {"Chrontel Inc","CHI"},
 {"Chunghwa Picture Tubes,LTD.","CHT"},
 {"Chunghwa Telecom Co., Ltd.","CTE"},
 {"Chunichi Denshi Co.,LTD.","KCD"},
 {"Chuomusen Co., Ltd. ","QQQ"},
 {"Chyron Corp","CGS"},
 {"Cine-tal","CNE"},
 {"Cipher Systems Inc","PTG"},
 {"Ciprico Inc","CIP"},
 {"Ciprico Inc","CPC"},
 {"Cirel Systemes","FPX"},
 {"Cirque Corporation","CRQ"},
 {"Cirrus Logic Inc","CIR"},
 {"Cirrus Logic Inc","CLI"},
 {"Cirtech (UK) Ltd","SNS"},
 {"CIS Technology Inc","WSC"},
 {"Cisco Systems Inc","CIS"},
 {"Citicom Infotech Private Limited","CIL"},
 {"Citifax Limited","CIT"},
 {"Citron GmbH","CIN"},
 {"Clarion Company Ltd","CLA"},
 {"Clarity Visual Systems","CVS"},
 {"Classe Audio","CLE"},
 {"Clevo Company","CLV"},
 {"Clinton Electronics Corp.","PPM"},
 {"Clone Computers","CLO"},
 {"Cloudium Systems Ltd.","CSL"},
 {"CMC Ltd","CMC"},
 {"C-Media Electronics","CMI"},
 {"CNet Technical Inc","JQE"},
 {"COBY Electronics Co., Ltd","COB"},
 {"CODAN Pty. Ltd.","COD"},
 {"Codec Inc.","COI"},
 {"Codenoll Technical Corporation","CDN"},
 {"COINT Multimedia Systems","CNT"},
 {"Colin.de","CDE"},
 {"Colorado MicroDisplay, Inc.","CMD"},
 {"Colorado Video, Inc.","CVI"},
 {"COM 1","MVX"},
 {"Comex Electronics AB","CMX"},
 {"Comm. Intelligence Corporation","CIC"},
 {"COMMAT L.t.d.","CLD"},
 {"Communications Specialies, Inc.","SDH"},
 {"Communications Supply Corporation (A division of WESCO)","INX"},
 {"Compal Electronics Inc","CPL"},
 {"Compaq Computer Company","CPQ"},
 {"Compound Photonics","CPP"},
 {"CompuAdd","CPD"},
 {"CompuMaster Srl","CMS"},
 {"Computer Diagnostic Systems","CDS"},
 {"Computer Peripherals Inc","CPI"},
 {"Computer Technology Corporation","CTP"},
 {"ComputerBoards Inc","CBI"},
 {"Computerm Corporation","CTM"},
 {"Computone Products","CTN"},
 {"Comrex","COX"},
 {"Comtec Systems Co., Ltd.","CTS"},
 {"Comtime GmbH","CMM"},
 {"Comtrol Corporation","COM"},
 {"Concept Development Inc","CDI"},
 {"Concept Solutions &amp; Engineering","CSE"},
 {"Concepts Inc","DCI"},
 {"Conexant Systems","CXT"},
 {"congatec AG","CGT"},
 {"Connect Int&#039;l A/S","CNI"},
 {"Connectware Inc","CWR"},
 {"CONRAC GmbH","CRC"},
 {"Consultancy in Advanced Technology","CAT"},
 {"Consumer Electronics Association","CEA"},
 {"CONTEC CO.,LTD.","CCJ"},
 {"Contec Company Ltd","CON"},
 {"Contemporary Research Corp.","CRH"},
 {"Control4 Corporation","CTR"},
 {"Convergent Data Devices","CDD"},
 {"Convergent Design Inc.","CDV"},
 {"Core Dynamics Corporation","CDC"},
 {"Corion Industrial Corporation","ART"},
 {"Core Technology Inc","COT"},
 {"CoreLogic","CLG"},
 {"Cornerstone Imaging","CRN"},
 {"Corollary Inc","COR"},
 {"Cosmic Engineering Inc.","CSM"},
 {"CoStar Corporation","COS"},
 {"CoSystems Inc","CTA"},
 {"Covia Inc.","CVA"},
 {"cPATH","CPT"},
 {"CRALTECH ELECTRONICA, S.L.","CRA"},
 {"Cray Communications","CDK"},
 {"CRE Technology Corporation","IOA"},
 {"Creative Labs Inc","CRE"},
 {"Creative Logic  ","CRL"},
 {"Creative Technology Ltd","CTL"},
 {"Creatix Polymedia GmbH","CTX"},
 {"Crescendo Communication Inc","CRS"},
 {"Cresta Systems Inc","CSD"},
 {"Crestron Electronics, Inc.","CEI"},
 {"Crio Inc.","CRI"},
 {"Cromack Industries Inc","CII"},
 {"Crystal Computer","XTL"},
 {"Crystal Semiconductor","CSC"},
 {"CrystaLake Multimedia","CLM"},
 {"CSS Laboratories","CSS"},
 {"CSTI Inc","CST"},
 {"CTC Communication Development Company Ltd","CTC"},
 {"Cubix Corporation","CUB"},
 {"Curtiss-Wright Controls, Inc.","CWC"},
 {"Cyberlabs","CYL"},
 {"CyberVision","CYB"},
 {"Cyberware","CYW"},
 {"Cybex Computer Products Corporation","CBX"},
 {"Cyclades Corporation","CYD"},
 {"Cylink Corporation","CYC"},
 {"Cyrix Corporation","CYX"},
 {"Cyrix Corporation","CRX"},
 {"Cytechinfo Inc","CYT"},
 {"Cyviz AS","CYV"},
 {"D&amp;M Holdings Inc, Professional Business Company","DMP"},
 {"D.N.S. Corporation","OPI"},
 {"DA2 Technologies Corporation","DDA"},
 {"DA2 Technologies Inc","DAW"},
 {"Daewoo Electronics Company Ltd","DWE"},
 {"Dai Telecom S.p.A.","TLT"},
 {"Daintelecom Co., Ltd","DIN"},
 {"DAIS SET Ltd.","DAI"},
 {"Daktronics","DAK"},
 {"Dale Computer Corporation","DCC"},
 {"Dancall Telecom A/S","DCT"},
 {"Danelec Marine A/S","DAN"},
 {"Danka Data Devices","DDD"},
 {"Daou Tech Inc","DAU"},
 {"DAT","HCA"},
 {"Data Apex Ltd","DAX"},
 {"Data Display AG","DDI"},
 {"Data Expert Corporation","DXP"},
 {"Data Export Corporation","EXP"},
 {"Data Modul AG","DMO"},
 {"Data Price Informatica","EBH"},
 {"Data Race Inc","DRI"},
 {"Data Ray Corp.","DRC"},
 {"Data Translation","DTX"},
 {"Data Video","DVT"},
 {"Databook Inc","DBK"},
 {"Datacast LLC","DCD"},
 {"Datacommunicatie Tron B.V.","TRN"},
 {"Datacube Inc","DQB"},
 {"Datadesk Technologies Inc","DDT"},
 {"Datakey Inc","DKY"},
 {"Datalogic Corporation","LJX"},
 {"Datang  Telephone Co","DTN"},
 {"Dataq Instruments Inc","DII"},
 {"Datasat Digital Entertainment","DDE"},
 {"Datatronics Technology Inc","DCV"},
 {"Datel Inc","DAT"},
 {"Datenerfassungs- und Informationssysteme","MSD"},
 {"Davicom Semiconductor Inc","DAV"},
 {"DAVIS AS","DAS"},
 {"DB Networks Inc","DBN"},
 {"DBA Hans Wedemeyer","HWC"},
 {"DCM Data Products","DCM"},
 {"Dearborn Group Technology","DGT"},
 {"DECIMATOR DESIGN PTY LTD","DXD"},
 {"Decros Ltd","DCR"},
 {"Deep Video Imaging Ltd","MLD"},
 {"DEI Holdings dba Definitive Technology","DFT"},
 {"Deico Electronics","DEI"},
 {"Dell Inc","DLL"},
 {"Dell Inc.","DEL"},
 {"Delphi Automotive LLP","DPH"},
 {"Delta Electronics Inc","DPC"},
 {"Delta Information Systems, Inc","DDV"},
 {"DELTATEC ","DTA"},
 {"Deltec Corporation","FPS"},
 {"DENON, Ltd.","DON"},
 {"Dension Audio Systems","DHD"},
 {"Densitron Computers Ltd","DEN"},
 {"Design &amp; Test Technology, Inc.","DTT"},
 {"Design Technology","LPI"},
 {"Deterministic Networks Inc.","DNI"},
 {"Deutsche Telekom Berkom GmbH","BCQ"},
 {"Deutsche Thomson OHG","DTO"},
 {"Devolo AG","DVL"},
 {"Dextera Labs Inc","DXL"},
 {"DFI","DFI"},
 {"DH Print","DHP"},
 {"Diadem","DIA"},
 {"Diagsoft Inc","DGS"},
 {"Dialogue Technology Corporation","DCO"},
 {"Diamond Computer Systems Inc","DCS"},
 {"Diamond Lane Comm. Corporation","DLC"},
 {"DiCon","DNV"},
 {"Dictaphone Corporation","DVD"},
 {"Diebold Inc.","DBD"},
 {"Digatron Industrie Elektronik GmbH","DAE"},
 {"DIGI International","DGI"},
 {"DigiBoard Inc","DBI"},
 {"Digicom S.p.A.","DIG"},
 {"Digicom Systems Inc","DMB"},
 {"Digicorp European sales S.A.","DGP"},
 {"Digiital Arts Inc","DGA"},
 {"Digipronix Control Systems","DXC"},
 {"Digital Acoustics Corporation","DAC"},
 {"Digital Audio Labs Inc","DAL"},
 {"Digital Communications Association","DCA"},
 {"Digital Discovery","SHR"},
 {"Schneider Electric Japan Holdings, Ltd.","PRF"},
 {"Digital Equipment Corporation","DEC"},
 {"Digital Processing Systems","DPS"},
 {"Digital Projection Limited","DPL"},
 {"DIGITAL REFLECTION INC.","DRD"},
 {"Digital Video System","DVS"},
 {"DigiTalk Pro AV","DPA"},
 {"Digital-Logic GmbH","DLG"},
 {"Digitan Systems Inc","DSI"},
 {"Digitelec Informatique Park Cadera","DLT"},
 {"Dimension Technologies, Inc.","DTE"},
 {"Dimond Multimedia Systems Inc","DMM"},
 {"Diseda S.A.","DIS"},
 {"Distributed Management Task Force, Inc. (DMTF) ","DMT"},
 {"Diversified Technology, Inc.","DTI"},
 {"D-Link Systems Inc","ABO"},
 {"D-Link Systems Inc","DLK"},
 {"DNA Enterprises, Inc.","DNA"},
 {"DO NOT USE - AUO","AUO"},
 {"DO NOT USE - LPL","LPL"},
 {"DO NOT USE - PHI","PHI"},
 {"DO NOT USE - PTW","PTW"},
 {"DO NOT USE - PVC","PVC"},
 {"DO NOT USE - RTK","RTK"},
 {"DO NOT USE - SEG","SEG"},
 {"DO NOT USE - TNJ","TNJ"},
 {"DO NOT USE - UND","UND"},
 {"DO NOT USE - UNE","UNE"},
 {"DO NOT USE - UNF","UNF"},
 {"DO NOT USE - WAN","WAN"},
 {"DO NOT USE - XER","XER"},
 {"DO NOT USE - XOC","XOC"},
 {"Doble Engineering Company","DBL"},
 {"DocuPoint","DPI"},
 {"Dolby Laboratories Inc. ","DLB"},
 {"Dolman Technologies Group Inc","DOL"},
 {"Domain Technology Inc","DSP"},
 {"DOME imaging systems","DMS"},
 {"Dome Imaging Systems","DOM"},
 {"Dongguan Alllike Electronics Co., Ltd.","AIK"},
 {"Dosch &amp; Amand GmbH &amp; Company KG","DUA"},
 {"Dotronic Mikroelektronik GmbH","DOT"},
 {"dPict Imaging, Inc.","DIM"},
 {"DpiX, Inc.","DPX"},
 {"DPT","DPT"},
 {"Dr. Bott KG","DRB"},
 {"Dr. Neuhous Telekommunikation GmbH","DNT"},
 {"Dragon Information Technology","DIT"},
 {"DRS Defense Solutions, LLC","DRS"},
 {"DS Multimedia Pte Ltd","DSD"},
 {"DSM Digital Services GmbH","DSM"},
 {"dSPACE GmbH","DCE"},
 {"DTC Tech Corporation","DTC"},
 {"DugoTech Co., LTD","DGK"},
 {"Dune Microsystems Corporation","DMC"},
 {"Dycam Inc","DYC"},
 {"Dymo-CoStar Corporation","DYM"},
 {"Dynamic Controls Ltd","DCL"},
 {"Dynax Electronics (HK) Ltd","DTK"},
 {"Dynax Electronics (HK) Ltd","DYX"},
 {"e.Digital Corporation","EDC"},
 {"E.E.P.D. GmbH","EEP"},
 {"Eagle Technology","EGL"},
 {"Eastman Kodak Company","KOD"},
 {"Eastman Kodak Company","EKC"},
 {"Easytel oy","TWI"},
 {"EBS Euchner Büro- und Schulsysteme GmbH","EBS"},
 {"Echo Speech Corporation","ECO"},
 {"Eclipse Tech Inc","ETI"},
 {"E-Cmos Tech Corporation","ECM"},
 {"Eden Sistemas de Computacao S/A","ESC"},
 {"Edimax Tech. Company Ltd","EDI"},
 {"EDMI","EDM"},
 {"Edsun Laboratories","ELI"},
 {"EE Solutions, Inc.","EES"},
 {"EEH Datalink GmbH","EEH"},
 {"Efficient Networks","ENI"},
 {"Egenera, Inc.","EGN"},
 {"Eicon Technology Corporation","EIC"},
 {"EIZO GmbH Display Technologies ","EGD"},
 {"Eizo Nanao Corporation","ENC"},
 {"EKSEN YAZILIM","EKS"},
 {"ELAD srl","ELA"},
 {"ELAN MICROELECTRONICS CORPORATION","ETD"},
 {"ELAN MICROELECTRONICS CORPORATION","TSH"},
 {"Elbit Systems of America","ESA"},
 {"ELCON Systemtechnik GmbH","ESG"},
 {"ELEA CardWare","LXS"},
 {"Elecom Company Ltd","ECP"},
 {"Elecom Company Ltd","ELE"},
 {"Electro Cam Corp.","ECA"},
 {"Electro Scientific Ind","ELC"},
 {"Electronic Measurements","MMM"},
 {"Electronic Trade Solutions Ltd","ETS"},
 {"Electronic-Design GmbH","EDG"},
 {"Electrosonic Ltd","ELL"},
 {"Element Labs, Inc.","ELT"},
 {"Elgato Systems LLC","EGA"},
 {"Elitegroup Computer Systems Company Ltd","ECS"},
 {"Elitegroup Computer Systems Company Ltd","UEG"},
 {"Elmeg GmbH Kommunikationstechnik","ELG"},
 {"Elmic Systems Inc","ELM"},
 {"ELMO COMPANY, LIMITED","EMO"},
 {"Elo TouchSystems Inc","ELO"},
 {"Elonex PLC","ELX"},
 {"El-PUSK Co., Ltd.","LPE"},
 {"ELSA GmbH","ELS"},
 {"ELTEC Elektronik AG","EAG"},
 {"Embedded computing inc ltd","EMB"},
 {"Embedded Solution Technology","EST"},
 {"Embrionix Design Inc.","EMD"},
 {"Emcore Corporation","EMK"},
 {"Emerging Display Technologies Corp","EDT"},
 {"EMG Consultants Inc","EMG"},
 {"EMiNE TECHNOLOGY COMPANY, LTD.","EME"},
 {"Empac","EPC"},
 {"Emulex Corporation","EMU"},
 {"Enciris Technologies","ECI"},
 {"Enciris Technologies ","ECT"},
 {"ENE Technology Inc.","ENE"},
 {"e-Net Inc","DTL"},
 {"Enhansoft","EHN"},
 {"ENIDAN Technologies Ltd","END"},
 {"Ensemble Designs, Inc","ESD"},
 {"Ensoniq Corporation","ENS"},
 {"Enterprise Comm. &amp; Computing Inc","ENT"},
 {"Envision Peripherals, Inc","EPI"},
 {"Eon Instrumentation, Inc. ","EON"},
 {"EPiCON Inc.","EPN"},
 {"Epiphan Systems Inc. ","EPH "},
 {"Epson Research","EHJ"},
 {"Equinox Systems Inc","EQX"},
 {"Equipe Electronics Ltd.","EQP"},
 {"Ergo Electronics","EGO"},
 {"Ergo System","ERG"},
 {"Ericsson Mobile Communications AB","ERI"},
 {"Ericsson Mobile Networks B.V.","EUT"},
 {"Ericsson, Inc.","ERN"},
 {"ES&amp;S","ESK"},
 {"eSATURNUS","ESN"},
 {"Escort Insturments Corporation","ERT"},
 {"ESS Technology Inc","ESS"},
 {"ESSential Comm. Corporation","ECC"},
 {"Esterline Technologies","ESL"},
 {"ScioTeq","ESB"},
 {"E-Systems Inc","ESY"},
 {"ET&amp;T Technology Company Ltd","EEE"},
 {"E-Tech Inc","ETT"},
 {"eTEK Labs Inc.","ETK"},
 {"Etherboot Project","ETH"},
 {"Eugene Chukhlomin Sole Proprietorship, d.b.a. ","ECK"},
 {"Euraplan GmbH","ERP"},
 {"Evans and Sutherland Computer","EAS"},
 {"Everex","EVX"},
 {"Everton Technology Company Ltd","ETC"},
 {"Evertz Microsystems Ltd.","ETL"},
 {"eviateg GmbH","EVI"},
 {"Ex Machina Inc","EMI"},
 {"Exacom SA","YHW"},
 {"Exatech Computadores &amp; Servicos Ltda","EXT"},
 {"Excel Company Ltd","ECL"},
 {"Excession Audio","EXC"},
 {"EXFO Electro Optical Engineering","XFO"},
 {"Exide Electronics","EXI"},
 {"Extended Systems, Inc.","ESI"},
 {"Exterity Ltd","EXY"},
 {"Extraordinary Technologies PTY Limited","CRO"},
 {"Exxact GmbH","EXX"},
 {"eyefactive Gmbh","EYF"},
 {"eyevis GmbH","EYE"},
 {"EzE Technologies","EZE"},
 {"F.J. Tieman BV","FJT"},
 {"Fairfield Industries","FFI"},
 {"Fantalooks Co., Ltd.","FAN"},
 {"Fanuc LTD","FNC"},
 {"Farallon Computing","FAR"},
 {"FARO Technologies","FRO"},
 {"Faroudja Laboratories","FLI"},
 {"Fast Multimedia AG","FMA"},
 {"FastPoint Technologies, Inc.","FTI"},
 {"Feature Integration Technology Inc.","FIT"},
 {"Fellowes &amp; Questec","FEL"},
 {"Fellowes, Inc.","FMI"},
 {"Fen Systems Ltd.","FEN"},
 {"Ferranti Int&#039;L","FER"},
 {"Ferrari Electronic GmbH","TLA"},
 {"FHLP","FHL"},
 {"Fibernet Research Inc","FRI"},
 {"Finecom Co., Ltd.","FIN"},
 {"Fingerprint Cards AB","FPC"},
 {"First Industrial Computer Inc","PCG"},
 {"First International Computer Inc","LEO"},
 {"First International Computer Ltd","FCG"},
 {"First Virtual Corporation","FVC"},
 {"Flat Connections Inc","FWR"},
 {"FlightSafety International","SSD"},
 {"FLY-IT Simulators","FIS"},
 {"FocalTech Systems Co., Ltd.","FTS"},
 {"Focus Enhancements, Inc.","FCS"},
 {"Fokus Technologies GmbH","FOK"},
 {"FOR-A Company Limited","FOA"},
 {"Force Computers","FRC"},
 {"Ford Microelectronics Inc","FMC"},
 {"Fore Systems Inc","FSI"},
 {"Forefront Int&#039;l Ltd","FIL"},
 {"Formosa Industrial Computing Inc","FIC"},
 {"Formoza-Altair","FMZ"},
 {"Forth Dimension Displays Ltd","FDD"},
 {"Forvus Research Inc","FRE"},
 {"Foss Tecator","FOS"},
 {"Founder Group Shenzhen Co.","FZC"},
 {"Fountain Technologies Inc","FTN"},
 {"Fraunhofer Heinrich-Hertz-Institute","HHI"},
 {"Freedom Scientific BLV","FRD"},
 {"FREEMARS Heavy Industries","TCX"},
 {"Frontline Test Equipment Inc.","FTE"},
 {"FTG Data Systems","FTG"},
 {"Fuji Xerox","FXX"},
 {"FUJIFILM Corporation","FFC"},
 {"Fujitsu Display Technologies Corp.","FDT"},
 {"Fujitsu General Limited.","FGL"},
 {"Fujitsu Ltd","FUJ"},
 {"Fujitsu Microelect Ltd","FML"},
 {"Fujitsu Peripherals Ltd","FPE"},
 {"Fujitsu Siemens Computers GmbH","FUS"},
 {"Fujitsu Spain","FJS"},
 {"Fujitsu Takamisawa Component Limited","FJC"},
 {"FUJITSU TEN LIMITED","FTL"},
 {"Funai Electric Co., Ltd.","FNI"},
 {"Furukawa Electric Company Ltd","FCB"},
 {"FURUNO ELECTRIC CO., LTD.","FEC"},
 {"Future Designs, Inc.","FDI"},
 {"Future Domain","FDC"},
 {"Future Systems Consulting KK","FSC"},
 {"Futuretouch Corporation","FTC"},
 {"FZI Forschungszentrum Informatik","FZI"},
 {"G&amp;W Instruments GmbH","SPH"},
 {"G. Diehl ISDN GmbH","GDI"},
 {"Gadget Labs LLC","GLS"},
 {"Gage Applied Sciences Inc","GAG"},
 {"GAI-Tronics, A Hubbell Company","HUB"},
 {"Galil Motion Control","GAL"},
 {"Garmin International","GRM"},
 {"Garnet System Company Ltd","GTM"},
 {"Gateway 2000","GWY"},
 {"Gateway Comm. Inc","GCI"},
 {"Gateworks Corporation","GWK"},
 {"Gaudi Co., Ltd.","GAU"},
 {"GCC Technologies Inc","GCC"},
 {"GDS","GDS"},
 {"GE Fanuc Embedded Systems","GEF"},
 {"Abaco Systems, Inc.","GEH"},
 {"Gefen Inc.","GFN"},
 {"Gem Plus","GEM"},
 {"GEMINI 2000 Ltd","GMN"},
 {"General Datacom","GDC"},
 {"General Dynamics C4 Systems","GED"},
 {"General Information Systems","GML"},
 {"General Inst. Corporation","GIC"},
 {"General Standards Corporation","GSC"},
 {"General Touch Technology Co., Ltd.","GTT"},
 {"Genesys ATE Inc","GEN"},
 {"Genesys Logic","GLM"},
 {"Gennum Corporation","GND"},
 {"GEO Sense","GEO"},
 {"Geotest Marvin Test Systems Inc","GTS"},
 {"GERMANEERS GmbH","GER"},
 {"GES Singapore Pte Ltd","GES"},
 {"Getac Technology Corporation","GET"},
 {"GFMesstechnik GmbH","GFM"},
 {"GI Provision Ltd","GIP"},
 {"Global Data SA","PST"},
 {"Global Village Communication","GVL"},
 {"GMK Electronic Design GmbH","GMK"},
 {"GMM Research Inc","GMM"},
 {"GMX Inc","GMX"},
 {"GN Nettest Inc","GNN"},
 {"GOEPEL electronic GmbH","GOE"},
 {"Goldmund - Digital Audio SA","GLD"},
 {"GOLD RAIN ENTERPRISES CORP.","GRE"},
 {"Goldstar Company Ltd","GSM"},
 {"Goldtouch","GTI"},
 {"Google Inc.","GGL"},
 {"GoPro, Inc.","GPR"},
 {"Granch Ltd","GRH"},
 {"Grand Junction Networks","GJN"},
 {"Grandstream Networks, Inc.","GSN"},
 {"Graphic SystemTechnology","GST"},
 {"Graphica Computer","GRA"},
 {"Graphtec Corporation","GTC"},
 {"Grass Valley Germany GmbH","TGV"},
 {"Grey Cell Systems Ltd","GCS"},
 {"Grossenbacher Systeme AG","GSY"},
 {"G-Tech Corporation","GTK"},
 {"Guillemont International","GIM"},
 {"GUNZE Limited","GZE"},
 {"Gunze Ltd","GNZ"},
 {"Guntermann &amp; Drunck GmbH","GUD"},
 {"Guzik Technical Enterprises","GUZ"},
 {"GVC Corporation","GVC"},
 {"H.P.R. Electronics GmbH","HPR"},
 {"Hagiwara Sys-Com Company Ltd","HSC"},
 {"GW Instruments","GWI"},
 {"Haider electronics","HAE"},
 {"Haivision Systems Inc.","HAI"},
 {"Halberthal","HAL"},
 {"Hall Research","HRI"},
 {"HAMAMATSU PHOTONICS K.K.","HPK"},
 {"Hampshire Company, Inc.","HTI"},
 {"Hanchang System Corporation","HAN"},
 {"HannStar Display Corp","HSD"},
 {"HannStar Display Corp","HSP"},
 {"HardCom Elektronik &amp; Datateknik","HDC"},
 {"Harman International Industries, Inc","HII"},
 {"Harris &amp; Jeffries Inc","HJI"},
 {"Harris Canada Inc","HWA"},
 {"Harris Corporation","HAR"},
 {"Harris Semiconductor","HRS"},
 {"Hauppauge Computer Works Inc","HCW"},
 {"Hayes Microcomputer Products Inc","HAY"},
 {"HCL America Inc","HCL"},
 {"HCL Peripherals","HCM"},
 {"HD-INFO d.o.o.","HDI"},
 {"Headplay, Inc.","HPI"},
 {"Heng Yu Technology (HK) Limited","HYT"},
 {"Hercules","HRC"},
 {"HERCULES","HRT"},
 {"HETEC Datensysteme GmbH","HET"},
 {"Hewlett Packard","HWP"},
 {"Hewlett Packard","HPD"},
 {"Hewlett-Packard Co.","HPC"},
 {"Hewlett-Packard Co.","HPQ"},
 {"Hexium Ltd.","HXM"},
 {"Hibino Corporation","HIB"},
 {"Highwater Designs Ltd","HWD"},
 {"Hikom Co., Ltd.","HIK"},
 {"Hilevel Technology","HIL"},
 {"HIRAKAWA HEWTECH CORP. ","HHC"},
 {"Hitachi America Ltd","HIT"},
 {"Hitachi Consumer Electronics Co., Ltd","HCE"},
 {"Hitachi Information Technology Co., Ltd.","HIC"},
 {"Hitachi Ltd","HTC"},
 {"Hitachi Maxell, Ltd.","MXL"},
 {"Hitachi Micro Systems Europe Ltd","HEL"},
 {"Hitex Systementwicklung GmbH","HTX"},
 {"hmk Daten-System-Technik BmbH","HMK"},
 {"HOB Electronic GmbH","HOB"},
 {"Holoeye Photonics AG","HOL"},
 {"Holografika kft.","HDV"},
 {"Holtek Microelectronics Inc","HTK"},
 {"Home Row Inc","INC"},
 {"HON HAI PRECISON IND.CO.,LTD.","FOX"},
 {"HONKO MFG. CO., LTD.","HKA"},
 {"Hope Industrial Systems, Inc.","HIS"},
 {"Horner Electric Inc","APG"},
 {"Horsent Technology Co., Ltd.","HST"},
 {"Hosiden Corporation","HOE"},
 {"HTBLuVA Mödling","HTL"},
 {"Hualon Microelectric Corporation","HMC"},
 {"HUALONG TECHNOLOGY CO., LTD","EBT"},
 {"Hughes Network Systems","HNS"},
 {"HUMAX Co., Ltd.","HMX"},
 {"HYC CO., LTD.","HYO"},
 {"Hydis Technologies.Co.,LTD","HYD"},
 {"Hynix Semiconductor","HYV"},
 {"Hypercope Gmbh Aachen","HYC"},
 {"Hypertec Pty Ltd","HYR"},
 {"Hyphen Ltd","HYP"},
 {"I&amp;T Telecom.","ITT"},
 {"I/OTech Inc","IOT"},
 {"IAT Germany GmbH","IAT"},
 {"IBM Brasil","IBM"},
 {"IBM Corporation","CDT"},
 {"IBP Instruments GmbH","IBP"},
 {"IBR GmbH","IBR"},
 {"IC Ensemble","ICE"},
 {"ICA Inc","ICA"},
 {"ICCC A/S","ICX"},
 {"ICD Inc","ICD"},
 {"ICET S.p.A.","ARE"},
 {"ICP Electronics, Inc./iEi Technology Corp.","ICP"},
 {"ICSL","IUC"},
 {"Icuiti Corporation","XTD"},
 {"Icuiti Corporation","IWR"},
 {"Id3 Semiconductors","ISC"},
 {"IDE Associates","IDE"},
 {"IDEO Product Development","IDO"},
 {"idex displays","DEX"},
 {"IDEXX Labs","IDX"},
 {"IDK Corporation","IDK"},
 {"Idneo Technologies","IDN"},
 {"IDTECH","ITS"},
 {"IEE","IEE"},
 {"IGM Communi","IGM"},
 {"IINFRA Co., Ltd","IIN"},
 {"Iiyama North America","IVM"},
 {"Ikegami Tsushinki Co. Ltd. ","IKE"},
 {"Ikos Systems Inc","IKS"},
 {"ILC","IND"},
 {"Image Logic Corporation","ILC"},
 {"Image Stream Medical","ISM"},
 {"IMAGENICS Co., Ltd.","IMG"},
 {"IMAGEQUEST Co., Ltd","IQT"},
 {"Imagraph","IME"},
 {"Imagraph","IMA"},
 {"ImasDe Canarias S.A.","IMD"},
 {"IMC Networks","IMC"},
 {"Immersion Corporation","IMM"},
 {"IMP Electronics Ltd.","HUM"},
 {"Impinj","IMP"},
 {"Impossible Production","IMN"},
 {"In Focus Systems Inc","IFS"},
 {"In4S Inc","ALD"},
 {"INBINE.CO.LTD","IBI"},
 {"Indtek Co., Ltd.","INK"},
 {"IneoQuest Technologies, Inc","IQI"},
 {"Industrial Products Design, Inc.","IPD"},
 {"Ines GmbH","INS"},
 {"Infineon Technologies AG","IFX"},
 {"Infinite Z","IFZ"},
 {"Informatik Information Technologies","IIT"},
 {"Informtech","IFT"},
 {"Infotek Communication Inc","ICI"},
 {"Infotronic America, Inc.","ITR"},
 {"Inframetrics Inc","INF"},
 {"Ingram Macrotron","VSN"},
 {"Ingram Macrotron Germany","VID"},
 {"InHand Electronics","IHE"},
 {"Initio Corporation","INI"},
 {"Inmax Technology Corporation","IMT"},
 {"Innolab Pte Ltd","INO"},
 {"InnoLux Display Corporation","INL"},
 {"InnoMedia Inc","INM"},
 {"Innotech Corporation","ILS"},
 {"Innovate Ltd","ATE"},
 {"Innovent Systems, Inc.","INN"},
 {"Innoware Inc","WII"},
 {"Inovatec S.p.A.","inu"},
 {"Inside Contactless","ICV"},
 {"Inside Out Networks","ION"},
 {"Insignia Solutions Inc","ISG"},
 {"INSIS Co., LTD.","ISR"},
 {"Institut f r angewandte Funksystemtechnik GmbH","IAF"},
 {"Integraph Corporation","ING"},
 {"Integrated Business Systems","IBC"},
 {"Integrated Device Technology, Inc.","IDP"},
 {"Integrated Tech Express Inc","ITE"},
 {"Integrated Tech Express Inc","SRC"},
 {"integrated Technology Express Inc","ITX"},
 {"Integration Associates, Inc.","IAI"},
 {"Intel Corp","ICO"},
 {"Intelligent Instrumentation","III"},
 {"Intelligent Platform Management Interface (IPMI) forum (Intel, HP, NEC, Dell)","IPI"},
 {"Intelliworxx, Inc.","IWX"},
 {"Intellix Corp.","SVC"},
 {"Interaction Systems, Inc","TCH"},
 {"Interactive Computer Products Inc","PEN"},
 {"Intercom Inc","ITC"},
 {"Interdigital Sistemas de Informacao","IDS"},
 {"Interface Corporation","FBI"},
 {"Interface Solutions","ISI"},
 {"Intergate Pty Ltd","IGC"},
 {"Interlace Engineering Corporation","IEC"},
 {"Interlink Electronics","IEI"},
 {"International Datacasting Corporation","IDC"},
 {"International Display Technology","IDT"},
 {"International Integrated Systems,Inc.(IISI)","ISY"},
 {"International Microsystems Inc","IMI"},
 {"International Power Technologies","IPT"},
 {"Internet Technology Corporation","ITD"},
 {"Interphase Corporation","INP"},
 {"Interphase Corporation","INT"},
 {"Intersil Corporation","LSD"},
 {"Intersolve Technologies","IST"},
 {"Inter-Tel","ITL"},
 {"Intertex Data AB","IXD"},
 {"Intervoice Inc","IVI"},
 {"Intevac Photonics Inc.","IVS"},
 {"Intracom SA","ICM"},
 {"Intrada-SDD Ltd","SDD"},
 {"IntreSource Systems Pte Ltd","ISP"},
 {"Intuitive Surgical, Inc.","SRG"},
 {"Inventec Corporation","INA"},
 {"Inventec Electronics (M) Sdn. Bhd.","INE"},
 {"Inviso, Inc.","INV"},
 {"I-O Data Device Inc","IOD"},
 {"i-O Display System","IOS"},
 {"Iomega","IOM"},
 {"IP Power Technologies GmbH ","IPP"},
 {"IP3 Technology Ltd.","IPQ"},
 {"IPC Corporation","IPC"},
 {"IPM Industria Politecnica Meridionale SpA","IPM"},
 {"IPS, Inc. (Intellectual Property Solutions, Inc.)","IPS"},
 {"IPWireless, Inc","IPW"},
 {"ISIC Innoscan Industrial Computers A/S","IIC"},
 {"Isolation Systems","ISL"},
 {"ISS Inc","ISS"},
 {"Itausa Export North America","ITA"},
 {"Ithaca Peripherals","IPR"},
 {"ITK Telekommunikation AG","ITK"},
 {"ITM inc.","ITM"},
 {"IT-PRO Consulting und Systemhaus GmbH","ITP"},
 {"Jace Tech Inc","JCE"},
 {"Jaeik Information &amp; Communication Co., Ltd.","JIC"},
 {"Jan Strapko - FOTO","XFG"},
 {"Janich &amp; Klass Computertechnik GmbH","JUK"},
 {"Janz Automationssysteme AG","JAS"},
 {"Japan Aviation Electronics Industry, Limited","JAE"},
 {"Japan Digital Laboratory Co.,Ltd.","JDL"},
 {"Japan Display Inc.","JDI"},
 {"Jaton Corporation","JAT"},
 {"JET POWER TECHNOLOGY CO., LTD.","JET"},
 {"Jetway Information Co., Ltd","JWY"},
 {"jetway security micro,inc","JTY"},
 {"Jiangsu Shinco Electronic Group Co., Ltd","SHI"},
 {"Jones Futurex Inc","JFX"},
 {"Jongshine Tech Inc","LTI"},
 {"Josef Heim KG","HKG"},
 {"JPC Technology Limited","JPC"},
 {"JS DigiTech, Inc","JSD"},
 {"JS Motorsports","JTS"},
 {"Junnila","TPJ"},
 {"Jupiter Systems","JUP"},
 {"Jupiter Systems, Inc.","JSI"},
 {"JVC","JVC"},
 {"JVC KENWOOD Corporation","JKC"},
 {"JWSpencer &amp; Co.","JWS"},
 {"Kansai Electric Company Ltd","SGE"},
 {"Kaohsiung Opto Electronics Americas, Inc.","HIQ"},
 {"Karn Solutions Ltd.","KSL"},
 {"Karna","KAR"},
 {"Katron Tech Inc","KTN"},
 {"Kayser-Threde GmbH","KTG"},
 {"KDDI Technology Corporation","KDT"},
 {"KDE","KDE"},
 {"KDS USA","KDS"},
 {"KEISOKU GIKEN Co.,Ltd.","KGL"},
 {"Kensington Microware Ltd","KML"},
 {"Kenwood Corporation","KWD"},
 {"KEPS","EPS"},
 {"Kesa Corporation","KES"},
 {"Key Tech Inc","KEY"},
 {"Key Tronic Corporation","KTK"},
 {"Keycorp Ltd","KCL"},
 {"KeyView","KVX"},
 {"Kidboard Inc","KBI"},
 {"KIMIN Electronics Co., Ltd.","KME"},
 {"Kinetic Systems Corporation","KSC"},
 {"King Phoenix Company","KPC"},
 {"King Tester Corporation","KSX"},
 {"Kingston Tech Corporation","KTC"},
 {"Kionix, Inc.","KIO"},
 {"KiSS Technology A/S","KIS"},
 {"Klos Technologies, Inc.","PVP"},
 {"Kobil Systems GmbH","KBL"},
 {"Kobil Systems GmbH","KOB"},
 {"Kodiak Tech","KDK"},
 {"Kofax Image Products","KFX"},
 {"Kollmorgen Motion Technologies Group","KOL"},
 {"KOLTER ELECTRONIC","KOE"},
 {"Komatsu Forest ","KFE "},
 {"Konica corporation","KNC"},
 {"Konica Technical Inc","KTI"},
 {"Kontron Electronik","TWE"},
 {"Kontron Embedded Modules GmbH","KEM"},
 {"Kontron Europe GmbH","KEU"},
 {"Korea Data Systems Co., Ltd.","KDM"},
 {"KOUZIRO Co.,Ltd.","KOU"},
 {"KOWA Company,LTD. ","KOW"},
 {"Kramer Electronics Ltd. International","KMR"},
 {"Krell Industries Inc.","KRL"},
 {"Kroma Telecom","KRM"},
 {"Kroy LLC","KRY"},
 {"K-Tech","KTE"},
 {"KUPA China Shenzhen Micro Technology Co., Ltd. Gold Institute","KSG"},
 {"Kurta Corporation","KUR"},
 {"Kvaser AB","KVA"},
 {"KYE Syst Corporation","KYE"},
 {"Kyocera Corporation","KYC"},
 {"Kyushu Electronics Systems Inc","KEC"},
 {"K-Zone International","KZN"},
 {"K-Zone International co. Ltd.","KZI"},
 {"L-3 Communications","LLL"},
 {"La Commande Electronique","LCE"},
 {"Labcal Technologies","LCT"},
 {"Labtec Inc","LTC"},
 {"Labway Corporation","LWC"},
 {"LaCie","LAC"},
 {"Laguna Systems","LAG"},
 {"Land Computer Company Ltd","LND"},
 {"LANETCO International","LNT"},
 {"Lanier Worldwide","LWW"},
 {"Lars Haagh ApS","LHA"},
 {"LASAT Comm. A/S","LAS"},
 {"Laser Master","LMT"},
 {"Laserdyne Technologies","LDN"},
 {"Lasergraphics, Inc.","LGX"},
 {"Latitude Comm.","LCM"},
 {"Lava Computer MFG Inc","LAV"},
 {"LCI","LCC"},
 {"Lectron Company Ltd","LEC"},
 {"Leda Media Products","LMP"},
 {"Legerity, Inc","LEG"},
 {"Leitch Technology International Inc.","LTV"},
 {"Lenovo","LNV"},
 {"Lenovo Beijing Co. Ltd.","LIN"},
 {"Lenovo Group Limited","LEN"},
 {"Lexical Ltd","LEX"},
 {"LEXICON","LCN"},
 {"Leutron Vision","PRS"},
 {"Lexmark Int&#039;l Inc","LMI"},
 {"LG Semicom Company Ltd","LGS"},
 {"LGIC","MAN"},
 {"LifeSize Communications","LSC"},
 {"Lighthouse Technologies Limited","LHT"},
 {"Lightware Visual Engineering","LWR"},
 {"Lightware, Inc","LTW"},
 {"Lightwell Company Ltd","LZX"},
 {"Likom Technology Sdn. Bhd.","LKM"},
 {"Linear Systems Ltd.","LNR"},
 {"Link Tech Inc","LNK"},
 {"Linked IP GmbH","LIP"},
 {"Lisa Draexlmaier GmbH","FGD"},
 {"Litelogic Operations Ltd","LOL"},
 {"Lite-On Communication Inc","LCI"},
 {"Lithics Silicon Technology","LIT"},
 {"Litronic Inc","LTN"},
 {"Locamation B.V.","LOC"},
 {"Loewe Opta GmbH","LOE"},
 {"Logic Ltd","LGC"},
 {"Logical Solutions","LSL"},
 {"Logicode Technology Inc","LOG"},
 {"Logitech Inc","LGI"},
 {"LogiDataTech Electronic GmbH","LDT"},
 {"Logos Design A/S","SGO"},
 {"Long Engineering Design Inc","LED"},
 {"Longshine Electronics Company","LCS"},
 {"Loughborough Sound Images","LSI"},
 {"LSI Japan Company Ltd","LSJ"},
 {"LSI Systems Inc","LSY"},
 {"LTS Scale LLC","LTS"},
 {"Lubosoft","LBO"},
 {"Lucent Technologies","LUC"},
 {"Lucent Technologies","LMG"},
 {"Lucidity Technology Company Ltd","LTK"},
 {"Lumagen, Inc.","LUM"},
 {"Lung Hwa Electronics Company Ltd","LHE"},
 {"Luxeon","LXN"},
 {"Luxxell Research Inc","LUX"},
 {"LVI Low Vision International AB","LVI"},
 {"LXCO Technologies AG","LXC"},
 {"MAC System Company Ltd","MAC"},
 {"Mac-Eight Co., LTD.","MEJ"},
 {"Macraigor Systems Inc","OCD"},
 {"Macrocad Development Inc.","VHI"},
 {"Macronix Inc","MXI"},
 {"Madge Networks","MDG"},
 {"Maestro Pty Ltd","MAE"},
 {"MAG InnoVision","MAG"},
 {"Magic Leap","MLP"},
 {"Magni Systems Inc","MCP"},
 {"MagTek Inc.","EKA"},
 {"Magus Data Tech","MDT"},
 {"Mainpine Limited","MPN"},
 {"Mainpine Limited","MUK"},
 {"Many CNC System Co., Ltd.","PAK"},
 {"Maple Research Inst. Company Ltd","MPL"},
 {"MARANTZ JAPAN, INC.","MJI"},
 {"Marconi Instruments Ltd","MIL"},
 {"Marconi Simulation &amp; Ty-Coch Way Training","MRC"},
 {"Marina Communicaitons","MCR"},
 {"Mark Levinson","MLN"},
 {"Mark of the Unicorn Inc","MTU"},
 {"Marseille, Inc.","MNI"},
 {"Marshall Electronics","MBM"},
 {"Mars-Tech Corporation","MTC"},
 {"Maruko &amp; Company Ltd","MRK"},
 {"MASPRO DENKOH Corp.","MSR"},
 {"Mass Inc.","MAS"},
 {"Matelect Ltd.","MEQ"},
 {"Matrox","MTX"},
 {"Mat&#039;s Computers","MCQ"},
 {"Matsushita Communication Industrial Co., Ltd.","WPA"},
 {"Matsushita Electric Ind. Company Ltd","MAT"},
 {"MaxCom Technical Inc","MTI"},
 {"MaxData Computer AG","VOB"},
 {"MaxData Computer GmbH &amp; Co.KG","MXD"},
 {"Maxpeed Corporation","MXP"},
 {"Maxtech Corporation","MXT"},
 {"MaxVision Corporation","MXV"},
 {"Maygay Machines, Ltd","DJP"},
 {"Maynard Electronics","MAY"},
 {"MAZeT GmbH","MAZ"},
 {"MBC","MBC"},
 {"McDATA Corporation","MCD"},
 {"McIntosh Laboratory Inc.","MLI"},
 {"MCM Industrial Technology GmbH","MIT"},
 {"MEC Electronics GmbH","CEM"},
 {"Medar Inc","MDR"},
 {"Media Technologies Ltd.","MTB"},
 {"Media Tek Inc.","MKC"},
 {"Media Vision Inc","MVI"},
 {"Media4 Inc","MDA"},
 {"Mediacom Technologies Pte Ltd","OWL"},
 {"Mediaedge Corporation","MEK"},
 {"MediaFire Corp.","MFR"},
 {"Mediasonic","FTR"},
 {"MediaTec GmbH","MTE"},
 {"Mediatek Corporation","MDK"},
 {"Mediatrix Peripherals Inc","MPI"},
 {"Medikro Oy","MRO"},
 {"Mega System Technologies Inc","MEC"},
 {"Mega System Technologies, Inc.","MGA"},
 {"Megasoft Inc","MSK"},
 {"Megatech R &amp; D Company","MGT"},
 {"Meld Technology","MEP"},
 {"MEN Mikroelectronik Nueruberg GmbH","MEN"},
 {"Mentor Graphics Corporation","MGC"},
 {"MEPCO","RLD"},
 {"MEPhI","PPD"},
 {"Merging Technologies","MRT"},
 {"Meridian Audio Ltd","MAL"},
 {"Messeltronik Dresden GmbH","MED"},
 {"MET Development Inc","MDV"},
 {"Meta Watch Ltd","MTA"},
 {"Metheus Corporation","MET"},
 {"Metricom Inc","MCM"},
 {"Metronics Inc","QCH"},
 {"Mettler Toledo","NET"},
 {"Metz-Werke GmbH &amp; Co KG","MCE"},
 {"M-G Technology Ltd","MGL"},
 {"Micom Communications Inc","MIC"},
 {"Micomsoft Co., Ltd.","MSX"},
 {"Micro Computer Systems","MCS"},
 {"Micro Design Inc","MDI"},
 {"Micro Display Systems Inc","MDS"},
 {"Micro Firmware","MFI"},
 {"Micro Industries","MCC"},
 {"Micro Solutions, Inc.","BPD"},
 {"Micro Systemation AB","MSA"},
 {"Micro Technical Company Ltd","JMT"},
 {"Microbus PLC","MBD"},
 {"Microcom","MNP"},
 {"MicroDatec GmbH","MDX"},
 {"MicroDisplay Corporation","MRD"},
 {"Microdyne Inc","MDY"},
 {"MicroField Graphics Inc","MFG"},
 {"Microlab","MPJ"},
 {"Microline","LAF"},
 {"Micrologica AG","MLG"},
 {"Micromed Biotecnologia Ltd","MMD"},
 {"Micromedia AG","MMA"},
 {"Micron Electronics Inc","MCN"},
 {"Micronics Computers","MCI"},
 {"micronpc.com","MIP"},
 {"Micronyx Inc","MYX"},
 {"Micropix Technologies, Ltd.","MPX"},
 {"MicroSlate Inc.","MSL"},
 {"Microsoft","PNP"},
 {"Microsoft","MSH"},
 {"Microsoft","PNG"},
 {"MicroSoftWare","WBN"},
 {"Microstep","MSI"},
 {"Microtec","MCT"},
 {"Micro-Tech Hearing Instruments","MTH"},
 {"MICROTEK Inc.","MKT"},
 {"Microtek International Inc.","MTK"},
 {"MicroTouch Systems Inc","MSY"},
 {"Microvision","MVS"},
 {"Microvitec PLC","MVD"},
 {"Microway Inc","MWY"},
 {"Midori Electronics","MDC"},
 {"Mikroforum Ring 3","SFT"},
 {"Milestone EPE","MLS"},
 {"Millennium Engineering Inc","MLM"},
 {"Millogic Ltd.","MLL"},
 {"Millson Custom Solutions Inc.","MCX"},
 {"Miltope Corporation","VTM"},
 {"Mimio – A Newell Rubbermaid Company","MIM"},
 {"MindTech Display Co. Ltd","MTD"},
 {"MindTribe Product Engineering, Inc.","FTW"},
 {"Mini Micro Methods Ltd","MNC"},
 {"Minicom Digital Signage","MIN"},
 {"MiniMan Inc","MMN"},
 {"Minnesota Mining and Manufacturing","MMF"},
 {"Miranda Technologies Inc","MRA"},
 {"Miratel","MRL"},
 {"Miro Computer Prod.","MIR"},
 {"miro Displays","MID"},
 {"Mistral Solutions [P] Ltd.","MSP"},
 {"Mitec Inc","MII"},
 {"Mitel Corporation","MTL"},
 {"Mitron computer Inc","MTR"},
 {"Mitsubishi Electric Corporation","MEL"},
 {"Mitsubishi Electric Engineering Co., Ltd.","MEE"},
 {"Mitsumi Company Ltd","KMC"},
 {"MJS Designs","MJS"},
 {"MK Seiko Co., Ltd.","MKS"},
 {"M-Labs Limited","OHW"},
 {"MMS Electronics","MMS"},
 {"Modesto PC Inc","FST"},
 {"MODIS","MDD"},
 {"Modular Industrial Solutions Inc","MIS"},
 {"Modular Technology","MOD"},
 {"Momentum Data Systems","MOM"},
 {"Monorail Inc","MNL"},
 {"Monydata","MYA"},
 {"Moreton Bay","MBV"},
 {"Moses Corporation","MOS"},
 {"Mosgi Corporation","MSV"},
 {"Motion Computing Inc.","MCO"},
 {"Motium","MTM"},
 {"motorola","MSU"},
 {"Motorola Communications Israel","MCL"},
 {"Motorola Computer Group","MCG"},
 {"Motorola UDS","MOT"},
 {"Mouse Systems Corporation","MSC"},
 {"M-Pact Inc","MPC"},
 {"mps Software GmbH","MPS"},
 {"MS Telematica","MST"},
 {"MSC Vertriebs GmbH","MEX"},
 {"MSI GmbH","MSG"},
 {"M-Systems Flash Disk Pioneers","MSF"},
 {"Mtron Storage Technology Co., Ltd.","MTN"},
 {"Multi-Dimension Institute","MUD"},
 {"Multimax","MMI"},
 {"Multi-Tech Systems","MTS"},
 {"Multiwave Innovation Pte Ltd","MWI"},
 {"Mutoh America Inc","MAI"},
 {"mware","MWR"},
 {"Mylex Corporation","MLX"},
 {"Myriad Solutions Ltd","MYR"},
 {"Myse Technology","WYS"},
 {"N*Able Technologies Inc","NBL"},
 {"NAD Electronics","NAD"},
 {"Naitoh Densei CO., LTD.","NDK"},
 {"Najing CEC Panda FPD Technology CO. ltd","NCP"},
 {"Nakano Engineering Co.,Ltd.","NAK"},
 {"Nakayo Relecommunications, Inc.","NYC"},
 {"Nanomach Anstalt","SCS"},
 {"Nasa Ames Research Center","ADR"},
 {"National DataComm Corporaiton","NDC"},
 {"National Display Systems","NDI"},
 {"National Instruments Corporation","NIC"},
 {"National Key Lab. on ISN","NBS"},
 {"National Semiconductor Corporation","NSC"},
 {"National Semiconductor Japan Ltd","TTB"},
 {"National Transcomm. Ltd","NTL"},
 {"Nationz Technologies Inc.","ZIC"},
 {"Natural Micro System","NMS"},
 {"NaturalPoint Inc.","NAT"},
 {"Navatek Engineering Corporation","NVT"},
 {"Navico, Inc.","NME"},
 {"Navigation Corporation","NAV"},
 {"Naxos Tecnologia","NAX"},
 {"NCR Corporation","DUN"},
 {"NCR Corporation","NCC"},
 {"NCR Electronics","NCR"},
 {"NDF Special Light Products B.V.","NDF"},
 {"NDS Ltd","DMV"},
 {"NEC Corporation","NEC"},
 {"NEC CustomTechnica, Ltd.","NCT"},
 {"NEC-Mitsubishi Electric Visual Systems Corporation","NMV"},
 {"NEO TELECOM CO.,LTD.","NEO"},
 {"Neomagic","NMX"},
 {"NeoTech S.R.L","NTC"},
 {"Netaccess Inc","NTX"},
 {"NetComm Ltd","NCL"},
 {"NetVision Corporation","NVC"},
 {"Network Alchemy","NAL"},
 {"Network Designers","NDL"},
 {"Network General","NGC"},
 {"Network Info Technology","NIT"},
 {"Network Peripherals Inc","NPI"},
 {"Network Security Technology Co","NST"},
 {"Networth Inc","NTW"},
 {"NeuroSky, Inc.","NSA"},
 {"NEUROTEC - EMPRESA DE PESQUISA E DESENVOLVIMENTO EM BIOMEDICINA","NEU"},
 {"New Tech Int&#039;l Company","NTI"},
 {"NewCom Inc","NCI"},
 {"Newisys, Inc.","NWS"},
 {"Newport Systems Solutions","NSS"},
 {"Nexgen","NXG"},
 {"Nexgen Mediatech Inc.,","NEX"},
 {"Nexiq Technologies, Inc.","NXQ"},
 {"Next Level Communications","NLC"},
 {"NextCom K.K.","NXC"},
 {"NingBo Bestwinning Technology CO., Ltd","NBT"},
 {"NINGBO BOIGLE DIGITAL TECHNOLOGY CO.,LTD","BOI"},
 {"Nippon Avionics Co.,Ltd","AVI"},
 {"NIPPONDENCHI CO,.LTD","GSB"},
 {"NISSEI ELECTRIC CO.,LTD","NSI"},
 {"Nissei Electric Company","NIS"},
 {"Nits Technology Inc.","NTS"},
 {"Nixdorf Company","NCA"},
 {"NNC","NNC"},
 {"Nokia Data","NDS"},
 {"Nokia Display Products","NOK"},
 {"Nokia Mobile Phones","NMP"},
 {"Norand Corporation","NOR"},
 {"Norcent Technology, Inc.","NCE"},
 {"NordicEye AB","NOE"},
 {"North Invent A/S","NOI"},
 {"Northgate Computer Systems","NCS"},
 {"Not Limited Inc","NOT"},
 {"NovaWeb Technologies Inc","NWP"},
 {"Novell Inc","NVL"},
 {"Nspire System Inc.","NSP"},
 {"N-trig Innovative Technologies, Inc.","NTR"},
 {"NTT Advanced Technology Corporation","NTT"},
 {"NU Inc.","NUI"},
 {"NU Technology, Inc.","NUG"},
 {"Number Five Software","NFS"},
 {"Nutech Marketing PTL","KNX"},
 {"NuVision US, Inc.","NVI"},
 {"Nuvoton Technology Corporation ","NTN"},
 {"Nvidia","NVD"},
 {"N-Vision","JEN"},
 {"NXP Semiconductors bv.","NXP"},
 {"NW Computer Engineering","NWC"},
 {"Oak Tech Inc","OAK"},
 {"Oasys Technology Company","OAS"},
 {"OBJIX Multimedia Corporation","OMC"},
 {"OCTAL S.A.","PCB"},
 {"Oculus VR, Inc.","OVR"},
 {"Odrac","ODR"},
 {"Office Depot, Inc.","ATV"},
 {"OKI Electric Industrial Company Ltd","OKI"},
 {"Oksori Company Ltd","OQI"},
 {"Oksori Company Ltd","OSR"},
 {"Olfan","OCN"},
 {"Olicom A/S","OLC"},
 {"Olidata S.p.A.","OLD"},
 {"Olitec S.A.","OLT"},
 {"Olitec S.A.","OLV"},
 {"Olivetti","OLI"},
 {"OLYMPUS CORPORATION","OLY"},
 {"OmniTek","OTK"},
 {"Omnitel","OMN"},
 {"Omron Corporation","OMR"},
 {"On Systems Inc","ONS"},
 {"Oneac Corporation","ONE"},
 {"ONKYO Corporation","ONK"},
 {"OnLive, Inc","ONL"},
 {"OOO Technoinvest","TIV"},
 {"Opcode Inc","OPC"},
 {"Open Connect Solutions","OCS"},
 {"OPEN Networks Ltd","ONW"},
 {"Open Stack, Inc.","OSI"},
 {"OPPO Digital, Inc.","OPP"},
 {"OPTi Inc","OPT"},
 {"Optibase Technologies","OBS"},
 {"Optical Systems Design Pty Ltd","OSD"},
 {"Option Industrial Computers","OIC"},
 {"Option International","OIN"},
 {"Option International","OIM"},
 {"OPTI-UPS Corporation","OSP"},
 {"Optivision Inc","OPV"},
 {"OPTO22, Inc.","OTT"},
 {"Optoma Corporation           ","OTM"},
 {"Optum Engineering Inc.","OEI"},
 {"Orchid Technology","OTI"},
 {"ORGA Kartensysteme GmbH","ORG"},
 {"Orion Communications Co., Ltd.","TOP"},
 {"ORION ELECTRIC CO., LTD.","ORN"},
 {"ORION ELECTRIC CO.,LTD","OEC"},
 {"OSAKA Micro Computer, Inc.","OSA"},
 {"OSR Open Systems Resources, Inc.","ORI"},
 {"OSRAM","OOS"},
 {"OUK Company Ltd","OUK"},
 {"outsidetheboxstuff.com","OTB"},
 {"Oxus Research S.A.","OXU"},
 {"OZ Corporation","OZC"},
 {"Pacific Avionics Corporation","PAC"},
 {"Pacific CommWare Inc","PCW"},
 {"Pacific Image Electronics Company Ltd","PIE"},
 {"Packard Bell Electronics","PBL"},
 {"Packard Bell NEC","PBN"},
 {"PACSGEAR, Inc.","PGI"},
 {"Padix Co., Inc.","QFF"},
 {"Pan Jit International Inc.","PJT"},
 {"Panasonic","MDO"},
 {"Panasonic Avionics Corporation","PLF"},
 {"Panasonic Industry Company","MEI"},
 {"Panelview, Inc.","PNL"},
 {"Pantel Inc","PTL"},
 {"PAR Tech Inc.","PTA"},
 {"Parade Technologies, Ltd.","PRT"},
 {"Paradigm Advanced Research Centre","PGM"},
 {"Parallan Comp Inc","PAR"},
 {"Parallax Graphics","PLX"},
 {"Parc d&#039;Activite des Bellevues","RCE"},
 {"Parrot","POT"},
 {"Pathlight Technology Inc","PTH"},
 {"PC Xperten","PCX"},
 {"PCBANK21","PCK"},
 {"PCM Systems Corporation","PCM"},
 {"PC-Tel Inc","PCT"},
 {"PD Systems International Ltd","PDS"},
 {"PDTS - Prozessdatentechnik und Systeme","PDT"},
 {"Pegatron Corporation","PEG"},
 {"PEI Electronics Inc","PEI"},
 {"Penta Studiotechnik GmbH","PVM"},
 {"pentel.co.,ltd","PCL"},
 {"Peppercon AG","PEP"},
 {"Perceptive Pixel Inc.","PPX"},
 {"Perceptive Signal Technologies","PER"},
 {"PerComm","PRC"},
 {"Performance Concepts Inc.,","PCO"},
 {"Performance Technologies","IPN"},
 {"Perle Systems Limited","PSL"},
 {"Perpetual Technologies, LLC","PON"},
 {"Peter Antesberger Messtechnik","PAM"},
 {"Peus-Systems GmbH","PSD"},
 {"Philips BU Add On Card","PCA"},
 {"Philips Communication Systems","PHS"},
 {"Philips Consumer Electronics Company","PHL"},
 {"Philips Medical Systems Boeblingen GmbH","PHE"},
 {"Philips Semiconductors","PSC"},
 {"Phoenix Contact","PXC"},
 {"Phoenix Technologies, Ltd.","PNX"},
 {"Phoenixtec Power Company Ltd","PPC"},
 {"Photonics Systems Inc.","PHO"},
 {"PhotoTelesis","RSC"},
 {"Phylon Communications","PHY"},
 {"PicPro","PPR"},
 {"Pijnenburg Beheer N.V.","PHC"},
 {"Pioneer Computer Inc","PCI"},
 {"Pioneer Electronic Corporation","PIO"},
 {"Pitney Bowes","PBV"},
 {"Pitney Bowes","PBI"},
 {"Pixel Qi","PQI"},
 {"Pixel Vision","PVN"},
 {"PIXELA CORPORATION","PXE"},
 {"Pixie Tech Inc","PIX"},
 {"Plain Tree Systems Inc","PTS"},
 {"Planar Systems, Inc.","PNR"},
 {"PLUS Vision Corp.","PLV"},
 {"PMC Consumer Electronics Ltd","PMC"},
 {"pmns GmbH","SPR"},
 {"Point Multimedia System","PMM"},
 {"Polycom Inc.","PLY"},
 {"PolyComp (PTY) Ltd.","POL"},
 {"Polycow Productions","COW"},
 {"Portalis LC","POR"},
 {"Poso International B.V.","ARO"},
 {"POTRANS Electrical Corp.","PEC"},
 {"PowerCom Technology Company Ltd","PCC"},
 {"Powermatic Data Systems","CPX"},
 {"Practical Electronic Tools","PET"},
 {"Practical Peripherals","PPI"},
 {"Practical Solutions Pte., Ltd.","PSE"},
 {"Praim S.R.L.","PRD"},
 {"Primax Electric Ltd","PEL"},
 {"Prime Systems, Inc.","SYX"},
 {"Prime view international Co., Ltd","PVI"},
 {"Princeton Graphic Systems","PGS"},
 {"Prism, LLC","PIM"},
 {"Priva Hortimation BV","PRI"},
 {"PRO/AUTOMATION","PRA"},
 {"Procomp USA Inc","PCP"},
 {"Prodea Systems Inc.","PSY"},
 {"Prodrive B.V.","PDV"},
 {"Projecta","PJA"},
 {"Projectavision Inc","DHT"},
 {"Projectiondesign AS","PJD"},
 {"PROLINK Microsystems Corp.","PLM"},
 {"Pro-Log Corporation","PLC"},
 {"Promate Electronic Co., Ltd.","PMT"},
 {"Prometheus","PRM"},
 {"Promise Technology Inc","PTI"},
 {"Promotion and Display Technology Ltd.","PAD"},
 {"Promotion and Display Technology Ltd.","TEL"},
 {"propagamma kommunikation","PGP"},
 {"Prosum","PSM"},
 {"Proteon","PRO"},
 {"Proview Global Co., Ltd","PVG"},
 {"Proxim Inc","PXM"},
 {"Proxima Corporation","PRX"},
 {"PS Technology Corporation","PTC"},
 {"Psion Dacom Plc.","PDM"},
 {"PSI-Perceptive Solutions Inc","PSI"},
 {"PT Hartono Istana Teknologi","PLT"},
 {"Pulse-Eight Ltd","PUL"},
 {"Pure Data Inc","PDR"},
 {"Purup Prepress AS","PPP"},
 {"Qingdao Haier Electronics Co., Ltd.","HRE"},
 {"Q-Logic","QLC"},
 {"Qtronix Corporation","QTR"},
 {"Quadram","DHQ"},
 {"Quadram","QDM"},
 {"Quadrant Components Inc","QCL"},
 {"QuakeCom Company Ltd","QCC"},
 {"Qualcomm Inc","QCP"},
 {"Quanta Computer Inc","QCI"},
 {"Quanta Display Inc.","QDS"},
 {"Quantum","QTM"},
 {"Quantum 3D Inc","QTD"},
 {"Quantum Data Incorporated","QDI"},
 {"Quartics","QVU"},
 {"Quatographic AG","QUA"},
 {"Questech Ltd","QTH"},
 {"Questra Consulting","QUE"},
 {"Quick Corporation","QCK"},
 {"Quickflex, Inc","QFI"},
 {"Quicknet Technologies Inc","QTI"},
 {"R Squared","RSQ"},
 {"R.P.T.Intergroups","RPT"},
 {"Racal Interlan Inc","RII"},
 {"Racal-Airtech Software Forge Ltd","TSF"},
 {"Racore Computer Products Inc","RAC"},
 {"Radicom Research Inc","RRI"},
 {"Radio Consult SRL","RCN"},
 {"RADIODATA GmbH","RDN"},
 {"RadioLAN Inc","RLN"},
 {"Radiospire Networks, Inc.","RSN"},
 {"Radisys Corporation","RAD"},
 {"Radius Inc","RDS"},
 {"RAFI GmbH &amp; Co. KG","RFI"},
 {"Rainbow Displays, Inc.","RDI"},
 {"Rainbow Technologies","RNB"},
 {"Raintree Systems","RTS"},
 {"Rainy Orchard","BOB"},
 {"Rampage Systems Inc","RSI"},
 {"Rancho Tech Inc","RAN"},
 {"Rancho Tech Inc","RTI"},
 {"Rapid Tech Corporation","RSX"},
 {"Raritan Computer, Inc","RMC"},
 {"Raritan, Inc.","RAR"},
 {"RAScom Inc","RAS"},
 {"RATOC Systems, Inc.","REX"},
 {"Raylar Design, Inc.","RAY"},
 {"RC International","RCI"},
 {"Reach Technology Inc","RCH"},
 {"Reakin Technolohy Corporation","RKC"},
 {"Real D","REA"},
 {"Realtek Semiconductor Company Ltd","RTL"},
 {"Realtek Semiconductor Corp.","ALG"},
 {"Realvision Inc","RVI"},
 {"ReCom","REC"},
 {"Red Wing Corporation","RWC"},
 {"Redfox Technologies Inc.","RFX"},
 {"Reflectivity, Inc.","REF"},
 {"Rehan Electronics Ltd.","REH"},
 {"Relia Technologies","RTC"},
 {"Reliance Electric Ind Corporation","REL"},
 {"Renesas Technology Corp.","REN"},
 {"Rent-A-Tech","RAT"},
 {"Research Electronics Development Inc","RED"},
 {"Research Machines","RMP"},
 {"ResMed Pty Ltd","RES"},
 {"Resonance Technology, Inc.","RET"},
 {"Restek Electric Company Ltd","WTS"},
 {"Reveal Computer Prod","RVL"},
 {"Revolution Display, Inc.","REV"},
 {"RGB Spectrum","RGB"},
 {"RGB Systems, Inc. dba Extron Electronics","EXN"},
 {"RICOH COMPANY, LTD.","RIC"},
 {"RightHand Technologies","RHD"},
 {"Rios Systems Company Ltd","RIO"},
 {"Ritech Inc","RIT"},
 {"Rivulet Communications","RIV"},
 {"Robert Bosch GmbH","BSG"},
 {"Robert Gray Company","GRY"},
 {"Robertson Geologging Ltd","RGL"},
 {"Robust Electronics GmbH ","ROB"},
 {"Rockwell Automation/Intecolor","RAI"},
 {"Rockwell Collins","RCO"},
 {"Rockwell Collins / Airshow Systems","ASY"},
 {"Rockwell Collins, Inc.","COL"},
 {"Rockwell International","ROK"},
 {"Rockwell Semiconductor Systems","RSS"},
 {"Rogen Tech Distribution Inc","MAX"},
 {"Rohde &amp; Schwarz","ROS"},
 {"Rohm Co., Ltd.","ROH"},
 {"Rohm Company Ltd","RHM"},
 {"Roland Corporation","RJA"},
 {"RoomPro Technologies","RPI"},
 {"Roper International Ltd","ROP"},
 {"Roper Mobile","RMT"},
 {"Ross Video Ltd","RSV"},
 {"Royal Information","TRL"},
 {"Rozsnyó, s.r.o.","RZS"},
 {"RSI Systems Inc","RVC"},
 {"RUNCO International","RUN"},
 {"S&amp;K Electronics","SNK"},
 {"S3 Inc","TLV"},
 {"S3 Inc","SIM"},
 {"S3 Inc","SSS"},
 {"Saab Aerotech","SAE"},
 {"Sage Inc","SAI"},
 {"SAGEM","SGM"},
 {"SAIT-Devlonics","SDK"},
 {"Saitek Ltd","SAK"},
 {"Salt Internatioinal Corp.","SLT"},
 {"Samsung Electric Company","SAM"},
 {"Samsung Electro-Mechanics Company Ltd","SKT"},
 {"Samsung Electronics America","STN"},
 {"Samsung Electronics America Inc","KYK"},
 {"Samsung Electronic Co.","SSE"},
 {"Samsung Electronics Company Ltd","SEM"},
 {"Samtron Displays Inc","SDI"},
 {"SANKEN ELECTRIC CO., LTD","JSK"},
 {"Sankyo Seiki Mfg.co., Ltd","SSJ"},
 {"Sanritz Automation Co.,Ltd.","SAA"},
 {"SANTAK CORP.","STK"},
 {"Santec Corporation","SOC"},
 {"Sanyo Electric Co.,Ltd.","SAN"},
 {"Sanyo Electric Company Ltd","SCD"},
 {"Sanyo Electric Company Ltd","SIB"},
 {"Sanyo Electric Company Ltd","TSC"},
 {"Sanyo Icon","ICN"},
 {"Sapience Corporation","SPN"},
 {"SAT (Societe Anonyme)","SDA"},
 {"SBS Technologies (Canada), Inc. (was Avvida Systems, Inc.)","AVV"},
 {"SBS-or Industrial Computers GmbH","SBS"},
 {"Scan Group Ltd","SGI"},
 {"Scanport, Inc.","SCN"},
 {"SCD Tech","KFC"},
 {"Sceptre Tech Inc","SPT"},
 {"Schlumberger","SMB"},
 {"Schlumberger Cards","SCH"},
 {"Schlumberger Technology Corporate","SLR"},
 {"Schneider &amp; Koch","SKD"},
 {"Schneider Electric S.A.","MGE"},
 {"Schnick-Schnack-Systems GmbH","SLS"},
 {"SCI Systems Inc.","REM"},
 {"SCM Microsystems Inc","SCM"},
 {"Scriptel Corporation","SCP"},
 {"SDR Systems","SDR"},
 {"SDS Technologies","STY"},
 {"SDX Business Systems Ltd","SDX"},
 {"Seanix Technology Inc","NIX"},
 {"Seanix Technology Inc.","SEA"},
 {"Sedlbauer","SAG"},
 {"SeeColor Corporation","SEE"},
 {"SeeCubic B.V.","SCB"},
 {"SeeReal Technologies GmbH","SRT"},
 {"Seiko Epson Corporation","SEC"},
 {"Seiko Instruments Information Devices Inc","SID"},
 {"Seiko Instruments USA Inc","SIU"},
 {"Seitz &amp; Associates Inc","SEI"},
 {"Sejin Electron Inc","SJE"},
 {"SELEX GALILEO","SXG"},
 {"Semtech Corporation","STH"},
 {"SendTek Corporation","SET"},
 {"Senseboard Technologies AB","SBT"},
 {"Sencore","SEN"},
 {"Sentelic Corporation","STU"},
 {"SEOS Ltd","SEO"},
 {"Sentronic International Corp.","SNC"},
 {"SEP Eletronica Ltda.","SEP"},
 {"Sequent Computer Systems Inc","SQT"},
 {"Session Control LLC","SES"},
 {"Setred","SRD"},
 {"SEVIT Co., Ltd.","SVT"},
 {"SGEG","SVA"},
 {"Seyeon Tech Company Ltd","SYT"},
 {"SGS Thomson Microelectronics","STM"},
 {"Shadow Systems","OYO"},
 {"Shanghai Bell Telephone Equip Mfg Co","SBC"},
 {"Shanghai Guowei Science and Technology Co., Ltd.","SGW"},
 {"SHANGHAI SVA-DAV ELECTRONICS CO., LTD","XQU"},
 {"Sharedware Ltd","SWL"},
 {"Shark Multimedia Inc","SMM"},
 {"SharkTec A/S","DFK"},
 {"Sharp Corporation","SHP"},
 {"SHARP TAKAYA ELECTRONIC INDUSTRY CO.,LTD.","SXT"},
 {"Shenzhen ChuangZhiCheng Technology Co., Ltd.","CZC"},
 {"Shenzhen Inet Mobile Internet Technology Co., LTD","IXN"},
 {"Shenzhen MTC Co., Ltd","SZM"},
 {"Shenzhen Ramos Digital Technology Co., Ltd","RMS"},
 {"Shenzhen South-Top Computer Co., Ltd.","SSL"},
 {"Shenzhen three Connaught Information Technology Co., Ltd. (3nod Group)","AZH"},
 {"Shenzhen Zhuona Technology Co., Ltd.","XYE"},
 {"Shenzhen ZhuoYi HengTong Computer Technology Limited","HTR"},
 {"Shenzhen Zowee Technology Co., LTD","ZWE"},
 {"Sherwood Digital Electronics Corporation","SDE"},
 {"ShibaSoku Co., Ltd.","SHC"},
 {"Shin Ho Tech","SHT"},
 {"Shlumberger Ltd","SLB"},
 {"Shuttle Tech","SAT"},
 {"Sichuan Changhong Electric CO, LTD.","CHG"},
 {"Sichuang Changhong Corporation","CHO"},
 {"Siemens","SIE"},
 {"Siemens AG","SDT"},
 {"SIEMENS AG","SIA"},
 {"Siemens Microdesign GmbH","SNI"},
 {"Siemens Nixdorf Info Systems","SNP"},
 {"Sierra Semiconductor Inc","SSC"},
 {"Sierra Wireless Inc.","SWI"},
 {"Sigma Designs Inc","SIG"},
 {"Sigma Designs, Inc.","SGD"},
 {"Sigmacom Co., Ltd.","SCL"},
 {"SigmaTel Inc","STL"},
 {"Signet","DXS"},
 {"SII Ido-Tsushin Inc","STE"},
 {"Silcom Manufacturing Tech Inc","SMT"},
 {"Silex technology, Inc.","SXD"},
 {"Silicom Multimedia Systems Inc","SMS"},
 {"Silicon Graphics Inc","SGX"},
 {"Silicon Image, Inc.","SII"},
 {"Silicon Integrated Systems Corporation","SIS"},
 {"Silicon Laboratories, Inc","SIL"},
 {"Silicon Library Inc.","SLH"},
 {"Silicon Optix Corporation","SOI"},
 {"Silitek Corporation","SLK"},
 {"SIM2 Multimedia S.P.A.","SPU"},
 {"Simple Computing","SMP"},
 {"Simplex Time Recorder Co.","SPX"},
 {"Singular Technology Co., Ltd.","SIN"},
 {"SINOSUN TECHNOLOGY CO., LTD","SNO"},
 {"Sirius Technologies Pty Ltd","SIR"},
 {"sisel muhendislik","FUN"},
 {"SITECSYSTEM CO., LTD.","STS"},
 {"Sitintel","SIT"},
 {"SKYDATA S.P.A.","SKY"},
 {"Smart Card Technology","SCT"},
 {"SMART Modular Technologies","SMA"},
 {"Smart Silicon Systems Pty Ltd","SPL"},
 {"Smart Tech Inc","STI"},
 {"SMART Technologies Inc.","SBI"},
 {"SMK CORPORATION","SMK"},
 {"Snell &amp; Wilcox","SNW"},
 {"SOBO VISION","MVM"},
 {"Socionext Inc.","SCX"},
 {"Sodeman Lancom Inc","LAN"},
 {"SODIFF E&amp;T CO., Ltd.","SDF"},
 {"Soft &amp; Hardware development Goldammer GmbH","SHG"},
 {"Softbed - Consulting &amp; Development Ltd","SBD"},
 {"Software Café","SWC"},
 {"Software Technologies Group,Inc.","SWT"},
 {"Solitron Technologies Inc","SOL"},
 {"Solomon Technology Corporation","SLM"},
 {"SolutionInside","SXL"},
 {"SOMELEC Z.I. Du Vert Galanta","ONX"},
 {"Sonitronix","HON"},
 {"Sonix Comm. Ltd","SNX"},
 {"Sony","SNY"},
 {"Sony","SON"},
 {"Sony Ericsson Mobile Communications Inc.","SER"},
 {"SORCUS Computer GmbH","SCO"},
 {"Sorcus Computer GmbH","SOR"},
 {"SORD Computer Corporation","SCC"},
 {"Sotec Company Ltd","SOT"},
 {"South Mountain Technologies, LTD","FRS"},
 {"SOYO Group, Inc","SOY"},
 {"SPACE-I Co., Ltd.","SPI"},
 {"SpaceLabs Medical Inc","SMI"},
 {"SPEA Software AG","SPE"},
 {"SpeakerCraft","SPK"},
 {"Specialix","SLX"},
 {"Spectragraphics Corporation","SGC"},
 {"Spectrum Signal Proecessing Inc","SSP"},
 {"SR-Systems e.K.","SRS"},
 {"S-S Technology Inc","SSI"},
 {"ST Electronics Systems Assembly Pte Ltd","STA"},
 {"STAC Electronics","STC"},
 {"Standard Microsystems Corporation","SMC"},
 {"Star Paging Telecom Tech (Shenzhen) Co. Ltd.","STT"},
 {"Starflight Electronics","STF"},
 {"Stargate Technology","SGT"},
 {"StarLeaf","SLF"},
 {"Starlight Networks Inc","STR"},
 {"Starwin Inc.","STW"},
 {"Static","SWS"},
 {"STB Systems Inc","STB"},
 {"STD Computer Inc","STD"},
 {"StereoGraphics Corp.","STG"},
 {"ST-Ericsson","STX"},
 {"STMicroelectronics","SMO"},
 {"Stollmann E+V GmbH","STO"},
 {"Stores Automated Systems Inc","SAS"},
 {"Storm Technology","EZP"},
 {"StreamPlay Ltd","STP"},
 {"Stryker Communications","SYK"},
 {"Subspace Comm. Inc","SUB"},
 {"Sumitomo Metal Industries, Ltd.","SML"},
 {"Summagraphics Corporation","SUM"},
 {"Sun Corporation","SCE"},
 {"Sun Electronics Corporation","SUN"},
 {"Sun Microsystems","SVI"},
 {"SUNNY ELEKTRONIK","SNN"},
 {"SunRiver Data System","SDS"},
 {"Super Gate Technology Company Ltd","SGL"},
 {"SuperNet Inc","SNT"},
 {"Supra Corporation","SUP"},
 {"Surenam Computer Corporation","SUR"},
 {"Surf Communication Solutions Ltd","SRF"},
 {"SVD Computer","SVD"},
 {"SVSI","SVS"},
 {"SY Electronics Ltd","SYE"},
 {"Sylvania Computer Products","SYL"},
 {"Symbios Logic Inc","SLI"},
 {"Symbol Technologies","ISA"},
 {"Symicron Computer Communications Ltd.","SYM"},
 {"Synaptics Inc","SYN"},
 {"Synopsys Inc","SPS"},
 {"Syntax-Brillian","SXB"},
 {"SYPRO Co Ltd","SYP"},
 {"Sysgration Ltd","SYS"},
 {"Syslogic Datentechnik AG","SLC"},
 {"Sysmate Company","SME"},
 {"Sysmate Corporation","SIC"},
 {"Sysmic","SYC"},
 {"Systec Computer GmbH","SGZ"},
 {"System Craft","SCI"},
 {"system elektronik GmbH","SEB"},
 {"Systeme Lauer GmbH&amp;Co KG","SLA"},
 {"Systems Enhancement","UPS"},
 {"SystemSoft Corporation","SST"},
 {"Systran Corporation","SCR"},
 {"SYVAX Inc","SYV"},
 {"T+A elektroakustik GmbH","TUA "},
 {"Taicom Data Systems Co., Ltd.","TCD"},
 {"Taicom International Inc","TMR"},
 {"Taiko Electric Works.LTD","TKC"},
 {"Taiwan Video &amp; Monitor Corporation","TVM"},
 {"Takahata Electronics Co.,Ltd.","KTD"},
 {"Tamura Seisakusyo Ltd","TAM"},
 {"Tandberg","TAA"},
 {"Tandberg Data Display AS","TDD"},
 {"Tandem Computer Europe Inc","TDM"},
 {"Tandon Corporation","TCC"},
 {"Tandy Electronics","TDY"},
 {"Taskit Rechnertechnik GmbH","TAS"},
 {"Tatung Company of America Inc","TCS"},
 {"Tatung UK Ltd","VIB"},
 {"Taugagreining hf","NRV"},
 {"Taxan (Europe) Ltd","TAX"},
 {"TDK USA Corporation","PMD"},
 {"TDT","TDT"},
 {"TDVision Systems, Inc.","TDV"},
 {"TEAC System Corporation","TEA"},
 {"TEC CORPORATION","CET"},
 {"TEAC America Inc","TCJ"},
 {"Tech Source Inc.","TEZ"},
 {"Techmedia Computer Systems Corporation","TMC"},
 {"Technical Concepts Ltd","TCL"},
 {"Technical Illusions Inc.","TIL"},
 {"TechniSat Digital GmbH","TSD"},
 {"Technology Nexus Secure Open Systems AB","NXS"},
 {"Technology Power Enterprises Inc","TPE"},
 {"TechnoTrend Systemtechnik GmbH","TTS"},
 {"Tecmar Inc","TEC"},
 {"Tecnetics (PTY) Ltd","TCN"},
 {"TECNIMAGEN SA","TNM"},
 {"Tecnovision","TVD"},
 {"Tectona SoftSolutions (P) Ltd.,","RXT"},
 {"Teknor Microsystem Inc","TKN"},
 {"Tekram Technology Company Ltd","TRM"},
 {"Tektronix Inc","TEK"},
 {"TEKWorx Limited","TWX"},
 {"Telecom Technology Centre Co. Ltd.","TCT"},
 {"Telecommunications Techniques Corporation","TTC"},
 {"Teleforce.,co,ltd","TLF"},
 {"Teleliaison Inc","TAT"},
 {"Telelink AG","TLK"},
 {"Teleprocessing Systeme GmbH","TPS"},
 {"Teles AG","TAG"},
 {"Teleste Educational OY","TLS"},
 {"TeleVideo Systems","TSI"},
 {"Telia ProSoft AB","PFT"},
 {"Telindus","TLD"},
 {"Telxon Corporation","TLX"},
 {"Tennyson Tech Pty Ltd","TNY"},
 {"Teradici","TDC"},
 {"TerraTec Electronic GmbH","TER"},
 {"Texas Insturments","TXN"},
 {"Texas Microsystem","TMI"},
 {"Textron Defense System","TXT"},
 {"The Concept Keyboard Company Ltd","CKC"},
 {"The Linux Foundation","LNX"},
 {"The Moving Pixel Company","PXL"},
 {"The NTI Group","ITN"},
 {"The OPEN Group","TOG"},
 {"The Panda Project","PAN"},
 {"The Phoenix Research Group Inc","PRG"},
 {"The Software Group Ltd","TSG"},
 {"Thermotrex Corporation","TMX"},
 {"Thinklogical","TLL"},
 {"Thomas-Conrad Corporation","TCO"},
 {"Thomson Consumer Electronics","TCR"},
 {"Thruput Ltd","TPT"},
 {"Thundercom Holdings Sdn. Bhd.","THN"},
 {"Tidewater Association","TWA"},
 {"Time Management, Inc.","TMM"},
 {"TimeKeeping Systems, Inc.","TKS"},
 {"Times (Shanghai) Computer Co., Ltd.","TPD"},
 {"TIPTEL AG","TIP"},
 {"Tixi.Com GmbH","TIX"},
 {"T-Metrics Inc.","TMT"},
 {"TNC Industrial Company Ltd","TNC"},
 {"Todos Data System AB","TAB"},
 {"TOEI Electronics Co., Ltd.","TOE"},
 {"TONNA","TON"},
 {"Top Victory Electronics ( Fujian ) Company Ltd","TPV"},
 {"TOPRE CORPORATION","TPK"},
 {"Topro Technology Inc","TPR"},
 {"Topson Technology Co., Ltd.","TTA"},
 {"TORNADO Company","SFM"},
 {"Torus Systems Ltd","TGS"},
 {"Torus Systems Ltd","TRS"},
 {"Toshiba America Info Systems Inc","TAI"},
 {"Toshiba America Info Systems Inc","TSB"},
 {"Dynabook Inc.","TOS"},
 {"Toshiba Corporation","TTP"},
 {"Toshiba Global Commerce Solutions, Inc.","TGC"},
 {"Toshiba Matsushita Display Technology Co., Ltd","LCD"},
 {"TOSHIBA PERSONAL COMPUTER SYSTEM CORPRATION","PCS"},
 {"TOSHIBA TELI CORPORATION","TLI"},
 {"Totoku Electric Company Ltd","TTK"},
 {"Tottori Sanyo Electric","TSE"},
 {"Tottori SANYO Electric Co., Ltd.","TSL"},
 {"Touch Panel Systems Corporation","TPC"},
 {"TouchKo, Inc.","TKO"},
 {"Touchstone Technology","TOU"},
 {"TouchSystems","TSY"},
 {"TOWITOKO electronics GmbH","TWK"},
 {"Transtex SA","CSB"},
 {"Transtream Inc","TST"},
 {"TRANSVIDEO","TSV"},
 {"Tremetrics","TRE"},
 {"Tremon Enterprises Company Ltd","RDM"},
 {"Trenton Terminals Inc","TTI"},
 {"Trex Enterprises","TRX"},
 {"Tribe Computer Works Inc","OZO"},
 {"Tricord Systems","TRI"},
 {"Tri-Data Systems Inc","TDS"},
 {"TRIDELITY Display Solutions GmbH","TTY"},
 {"Trident Microsystem Inc","TRD"},
 {"Trident Microsystems Ltd","TMS"},
 {"TriGem Computer Inc","TGI"},
 {"TriGem Computer,Inc.","TGM"},
 {"Trigem KinfoComm","TIC"},
 {"Trioc AB","TRC"},
 {"Triple S Engineering Inc","TBB"},
 {"Tritec Electronic AG","TRT"},
 {"TriTech Microelectronics International","TRA"},
 {"Triumph Board a.s.","TRB "},
 {"Trivisio Prototyping GmbH","TRV"},
 {"Trixel Ltd","TXL"},
 {"Trtheim Technology","MKV"},
 {"Truevision","TVI"},
 {"TTE, Inc.","TTE"},
 {"Tulip Computers Int&#039;l B.V.","TCI"},
 {"Turbo Communication, Inc","TBC"},
 {"Turtle Beach System","TBS"},
 {"Tut Systems","TUT"},
 {"TV Interactive Corporation","TVR"},
 {"TV One Ltd","TVO"},
 {"TV1 GmbH","TVV"},
 {"TVS Electronics Limited","TVS"},
 {"Twinhead International Corporation","TWH"},
 {"Tyan Computer Corporation","TYN"},
 {"U. S. Electronics Inc.","USE"},
 {"U.S. Naval Research Lab","NRL"},
 {"U.S. Navy","TSP"},
 {"U.S. Digital Corporation","USD"},
 {"U.S. Robotics Inc","USR"},
 {"Ubinetics Ltd.","UBL"},
 {"Ueda Japan Radio Co., Ltd.","UJR"},
 {"UFO Systems Inc","UFO"},
 {"Ultima Associates Pte Ltd","UAS"},
 {"Ultima Electronics Corporation","UEC"},
 {"Ultra Network Tech","ULT"},
 {"Umezawa Giken Co.,Ltd","UMG"},
 {"Ungermann-Bass Inc","UBI"},
 {"Unicate","UNY"},
 {"Uniden Corporation","UDN"},
 {"Uniform Industrial Corporation","UIC"},
 {"Uniform Industry Corp.","UNI"},
 {"UNIGRAF-USA","UFG"},
 {"Unisys Corporation","UNB"},
 {"Unisys Corporation","UNC"},
 {"Unisys Corporation","UNM"},
 {"Unisys Corporation","UNO"},
 {"Unisys Corporation","UNS"},
 {"Unisys Corporation","UNT"},
 {"Unisys DSD","UNA"},
 {"Uni-Take Int&#039;l Inc.","WKH"},
 {"United Microelectr Corporation","UMC"},
 {"Unitop","UNP"},
 {"Universal Electronics Inc","UEI"},
 {"Universal Empowering Technologies","UET"},
 {"Universal Multimedia","UMM"},
 {"Universal Scientific Industrial Co., Ltd.","USI"},
 {"University College","JGD"},
 {"Uniwill Computer Corp.","UWC"},
 {"Up to Date Tech","UTD"},
 {"UPPI","UPP"},
 {"Ups Manufactoring s.r.l.","RUP"},
 {"USC Information Sciences Institute","ASD"},
 {"Utimaco Safeware AG","USA"},
 {"Vaddio, LLC","VAD"},
 {"Vadem","VDM"},
 {"VAIO Corporation","VAI"},
 {"Valence Computing Corporation","VAL"},
 {"Valley Board Ltda","VBT"},
 {"ValleyBoard Ltda.","VLB"},
 {"Valve Corporation","VLV"},
 {"VanErum Group","ITI"},
 {"Varian Australia Pty Ltd","VAR"},
 {"VATIV Technologies","VTV"},
 {"VBrick Systems Inc.","VBR"},
 {"VCONEX","VCX"},
 {"VDC Display Systems","VDC"},
 {"Vector Informatik GmbH","VEC"},
 {"Vector Magnetics, LLC","VCM"},
 {"Vektrex","VEK"},
 {"VeriFone Inc","VFI"},
 {"Vermont Microsystems","VMI"},
 {"Vestax Corporation","VTX"},
 {"Vestel Elektronik Sanayi ve Ticaret A. S.","VES"},
 {"Via Mons Ltd.","VIM"},
 {"VIA Tech Inc","VIA"},
 {"Victor Company of Japan, Limited","VCJ"},
 {"Victor Data Systems","VDA"},
 {"Victron B.V.","VIC"},
 {"Video &amp; Display Oriented Corporation","VDO"},
 {"Video Computer S.p.A.","URD"},
 {"Video International Inc.","JWD"},
 {"Video Products Inc","VPI"},
 {"VideoLan Technologies","VLT"},
 {"VideoServer","VSI"},
 {"Videotechnik Breithaupt","VTB"},
 {"VIDEOTRON CORP.","VTN"},
 {"Vidisys GmbH &amp; Company","VDS"},
 {"Viditec, Inc.","VDT"},
 {"ViewSonic Corporation","VSC"},
 {"Viewteck Co., Ltd.","VTK"},
 {"Viking Connectors","VIK"},
 {"Vinca Corporation","VNC"},
 {"Vinci Labs","NHT"},
 {"Vine Micros Limited","VML"},
 {"Vine Micros Ltd","VIN"},
 {"Virtual Computer Corporation","VCC"},
 {"Virtual Resources Corporation","VRC"},
 {"Vision Quest","VQ@"},
 {"Vision Systems GmbH","VSP"},
 {"Visioneer","VIS"},
 {"Visitech AS","VIT"},
 {"Vislink International Ltd","VLK"},
 {"VistaCom Inc","VCI"},
 {"Visual Interface, Inc","VIR"},
 {"Vivid Technology Pte Ltd","VTL"},
 {"VIZIO, Inc","VIZ"},
 {"VLSI Tech Inc","VTI"},
 {"VMware Inc.,","VMW"},
 {"Voice Technologies Group Inc","VTG"},
 {"Vortex Computersysteme GmbH","GDT"},
 {"VPixx Technologies Inc.","VPX"},
 {"VRmagic Holding AG","VRM"},
 {"V-Star Electronics Inc.","VSR"},
 {"VTech Computers Ltd","VTS"},
 {"VTel Corporation","VTC"},
 {"Vutrix (UK) Ltd","VUT"},
 {"Vweb Corp.","VWB"},
 {"Wacom Tech","WAC"},
 {"Wallis Hamilton Industries","JPW"},
 {"Wanlida Group Co., Ltd.","MLT"},
 {"Wave Access","WAL"},
 {"Wave Systems","AWS"},
 {"Wave Systems Corporation","WVM"},
 {"Wavephore","WAV"},
 {"Way2Call Communications","SEL"},
 {"WB Systemtechnik GmbH","WBS"},
 {"W-DEV","WEL "},
 {"Wearnes Peripherals International (Pte) Ltd","WPI"},
 {"Wearnes Thakral Pte","WTK"},
 {"WebGear Inc","WEB"},
 {"Westermo Teleindustri AB","WMO"},
 {"Western Digital","WDC"},
 {"Westinghouse Digital Electronics","WDE"},
 {"WEY Design AG","WEY"},
 {"Whistle Communications","WHI"},
 {"Wildfire Communications Inc","WLD"},
 {"WillNet Inc.","WNI"},
 {"Winbond Electronics Corporation","WEC"},
 {"Diebold Nixdorf Systems GmbH","WNX"},
 {"Winmate Communication Inc","WMT"},
 {"Winnov L.P.","WNV"},
 {"WiNRADiO Communications","WRC"},
 {"Wintop Technology Inc","WIN"},
 {"Wipotec Wiege- und Positioniersysteme GmbH","WWP"},
 {"WIPRO Information Technology Ltd","WIL"},
 {"Wipro Infotech","WIP"},
 {"Wireless And Smart Products Inc.","WSP"},
 {"Wisecom Inc","WCI"},
 {"Wistron Corporation","WST"},
 {"Wolfson Microelectronics Ltd","WML"},
 {"WolfVision GmbH","WVV"},
 {"Woodwind Communications Systems Inc","WCS"},
 {"Wooyoung Image &amp; Information Co.,Ltd.","WYT"},
 {"WorkStation Tech","WTI"},
 {"World Wide Video, Inc.","WWV"},
 {"Woxter Technology Co. Ltd","WXT"},
 {"X-10 (USA) Inc","XTN"},
 {"X2E GmbH","XTE"},
 {"XAC Automation Corp","XAC"},
 {"XDM Ltd.","XDM"},
 {"Xedia Corporation","MAD"},
 {"Xilinx, Inc.","XLX"},
 {"Xinex Networks Inc","XIN"},
 {"Xiotech Corporation","XIO"},
 {"Xircom Inc","XRC"},
 {"Xitel Pty ltd","XIT"},
 {"Xirocm Inc","XIR"},
 {"XN Technologies, Inc.","XNT"},
 {"XOCECO","UHB"},
 {"XORO ELECTRONICS (CHENGDU) LIMITED","XRO"},
 {"XS Technologies Inc","XST"},
 {"Xscreen AS","XSN"},
 {"XSYS","XSY"},
 {"Yamaha Corporation","YMH"},
 {"Xycotec Computer GmbH","XYC"},
 {"Yasuhiko Shirai Melco Inc","BUF"},
 {"Y-E Data Inc","YED"},
 {"Yokogawa Electric Corporation","YHQ"},
 {"Ypoaz Systems Inc","TPZ"},
 {"Z Microsystems","ZMZ"},
 {"Z3 Technology","ZTT"},
 {"Zalman Tech Co., Ltd.","ZMT"},
 {"Zandar Technologies plc","ZAN"},
 {"ZeeVee, Inc.","ZAZ"},
 {"Zebra Technologies International, LLC","ZBR"},
 {"Zefiro Acoustics","ZAX"},
 {"ZeitControl cardsystems GmbH","ZCT"},
 {"ZENIC Inc.","ZEN"},
 {"Zenith Data Systems","ZDS"},
 {"Zenith Data Systems","ZGT"},
 {"Zenith Data Systems","ZSE"},
 {"Zetinet Inc","ZNI"},
 {"Zhejiang Tianle Digital Electric Co., Ltd. ","TLE"},
 {"Zhong Shan City Richsound Electronic Industrial Ltd. ","RSR"},
 {"Znyx Adv. Systems","ZNX"},
 {"Zoom Telephonics Inc","ZTI"},
 {"Zoran Corporation","ZRN"},
 {"Zowie Intertainment, Inc","ZOW"},
 {"ZT Group Int&#039;l Inc.","ZTM"},
 {"ZTE Corporation","ZTE"},
 {"Zuniq Data Corporation","SIX"},
 {"Zydacron Inc","ZYD"},
 {"ZyDAS Technology Corporation","ZTC"},
 {"Zypcom Inc","ZYP"},
 {"Zytex Computers","ZYT"},
 {"Zytor Communications","HPA"},
 {"Alpha Electronics Company","AEJ"},
 {"BOE","BOE"},
 {"Chaplet Systems Inc","FIR"},
 {"Chenming Mold Ind. Corp.","CMG"},
 {"coolux GmbH","COO"},
 {"Data General Corporation","DGC"},
 {"Exabyte","EXA"},
 {"Herolab GmbH","HRL"},
 {"Hitachi Computer Products Inc","HCP"},
 {"Integrated Circuit Systems","ICS"},
 {"Irdata","IRD"},
 {"Jewell Instruments, LLC","JWL"},
 {"MultiQ Products AB","MQP"},
 {"Ncast Corporation","NAC"},
 {"ODME Inc.","ODM"},
 {"Photomatrix","PMX"},
 {"Quantum Solutions, Inc.","QSI"},
 {"Red Hat, Inc.","RHT"},
 {"Zyxel","ZYX"},
 {"Carrera Computer Inc","JAZ"},
 {"Chunghwa Picture Tubes, LTD","CGA"},
 {"eMicro Corporation","EMC"},
 {"Hisense Electric Co., Ltd.","HEC"},
 {"PanaScope","PNS"},
 {"SpinCore Technologies, Inc","SPC"},
 {"Sensics, Inc.","SVR"},
 {"IAdea Corporation","IAD"},
 {"Express Industrial, Ltd.","ELU"},
 {"Hewlett Packard Enterprise ","HPE"},
 {"Klipsch Group, Inc ","KGI"},
 {"Tek Gear","TKG"},
 {"HangZhou ZMCHIVIN","ZMC"},
 {"HTC Corportation","HVR"},
 {"Zebax Technologies","ZBX"},
 {"Guangzhou Shirui Electronics Co., Ltd.","SWO"},
 {"Picturall Ltd.","PIC"},
 {"Guangzhou Teclast Information Technology Limited","SKM"},
 {"GreenArrays, Inc.","GAC"},
 {"Thales Avionics","TAV"},
 {"Explorer Inc.","EXR"},
 {"Avegant Corporation","AVG"},
 {"MicroImage Video Systems","MIV"},
 {"ASUSTek COMPUTER INC","AUS"},
 {"Synthetel Corporation","STQ"},
 {"HP Inc.","HPN"},
 {"MicroTechnica Co.,Ltd.","MTJ"},
 {"Gechic Corporation","GEC"},
 {"MPL AG, Elektronik-Unternehmen","MEU"},
 {"Display Solution AG","DSA"},
 {"UEFI Forum","PRP"},
 {"Taitex Corporation","TTX"},
 {"EchoStar Corporation","ECH"},
 {"TCL Corporation","TOL"},
 {"ADDER TECHNOLOGY LTD","ADZ"},
 {"HKC OVERSEAS LIMITED","HKC"},
 {"KEYENCE CORPORATION","KYN"},
 {"TETRADYNE CO., LTD.","TET"},
 {"Abaco Systems, Inc.","ABS"},
 {"Meta Company","MVN"},
 {"Eizo Rugged Solutions","ERS"},
 {"VersaLogic Corporation","VLC"},
 {"CYPRESS SEMICONDUCTOR CORPORATION","CYP"},
 {"MILDEF AB","MDF"},
 {"FOVE INC","FOV"},
 {"INNES","NES"},
 {"Hoffmann + Krippner GmbH","HUK"},
 {"Axell Corporation","AXE"},
 {"UltiMachine","UMT"},
 {"TPK Holding Co., Ltd","KPT"},
 {"AAEON Technology Inc.","AAN"},
 {"Six15 Technologies","TDG"},
 {"Inlife-Handnet Co., Ltd.","IVR"},
 {"VR Technology Holdings Limited  ","DSJ"},
 {"Pimax Tech. CO., LTD ","PVR"},
 {"Total Vision LTD ","TVL"},
 {"Shanghai Lexiang Technology Limited  ","DPN"},
 {"Black Box Corporation","BBX"},
 {"TRAPEZE GROUP ","TRP"},
 {"Pabian Embedded Systems  ","PMS"},
 {"Televic Conference  ","TCF"},
 {"Shanghai Chai Ming Huang Info&amp;Tech Co, Ltd  ","HYL"},
 {"Techlogix Networx","TLN"},
 {"G2TOUCH KOREA","GGT"},
 {"MediCapture, Inc.","MVR"},
 {"HOYA Corporation PENTAX Lifecare Division","PNT"},
 {"christmann informationstechnik + medien GmbH &amp; Co. KG","CHR"},
 {"Tencent","TEN"},
 {"VRstudios, Inc.","VRS"},
 {"Extreme Engineering Solutions, Inc.","XES"},
 {"NewTek","NTK"},
 {"BlueBox Video Limited","BBV"},
 {"Televés, S.A.","TEV"},
 {"Avatron Software Inc.","AVS"},
 {"Positivo Tecnologia S.A.","POS"},
 {"VRgineers, Inc.","VRG"},
 {"Noritake Itron Corporation","NRI"},
 {"Matrix Orbital Corporation","MOC"},
 {"Elegant Invention","EIN"},
 {"Immersive Audio Technologies France","IMF"},
 {"Lightspace Technologies","LSP"},
 {"PixelNext Inc","PXN"},
 {"VRSHOW Technology Limited","TSW"},
 {"SONOVE GmbH","SNV"},
 {"Silex Inside","SXI"},
 {"Huawei Technologies Co., Inc. ","HWV"},
 {"Varjo Technologies","VRT"},
 {"Japan E.M.Solutions Co., Ltd.","JEM"},
 {"QD Laser, Inc.","QDL"},
 {"VADATECH INC","VAT"},
 {"Medicaroid Corporation","MCJ"},
 {"Razer Taiwan Co. Ltd.","RZR"},
 {"GIGA-BYTE TECHNOLOGY CO., LTD.","GBT"},
 {"Kontron GmbH","KOM"},
 {"Convergent Engineering, Inc.","CIE"},
 {"WyreStorm Technologies LLC ","WYR"},
 {"Astro HQ LLC","AHQ "},
 {"QSC, LLC","QSC"},
 {"Dimension Engineering LLC","DMN"},
 {"Shenzhen Dlodlo Technologies Co., Ltd.","DLO"},
 {"LENOVO BEIJING CO. LTD.","VLM"},
 {"Cammegh Limited","CRW"},
 {"Beihai Century Joint Innovation Technology Co.,Ltd","LHC"},
 {"Findex, Inc.","FDX"},
 {"Express Luck, Inc.","ELD"},
 {"LLC SKTB “SKIT”","SKI"},
 {"WOLF Advanced Technology","WLF"},
 {"BILD INNOVATIVE TECHNOLOGY LLC","BLD"},
 {"MIMO Monitors","MMT"},
 {"Icron","ICR"},
 {"TECNART CO.,LTD.","PIS"},
 {"Moxa Inc.","MHQ"},
 {"Disguise Technologies","DSG"},
 {"Comark LLC","CMK"},
 {"Megapixel Visual Realty","MPV"},
 {"Skyworth","SKW"},
 {"Meta View, Inc.","CFR"},
 {"MILCOTS","MLC"},
 {"NZXT (PNP same EDID)_","NXT"},
 {"Unicompute Technology Co., Ltd.","UTC"},
 {"TECHNOGYM S.p.A.","TGW"},
 {"Clover Electronics","CLR"},
 {"Kyokko Communication System Co., Ltd.","KTS"},
 {"Terumo Corporation","TMO"},
 {"Micro-Star Int&#039;l Co., Ltd.","CND"},
 {"Newline Interactive Inc.","NWL"},
 {"CORSAIR MEMORY Inc.","CRM"},
 {"aviica","VAV"},
 {"Monoprice.Inc","DMG"},
 {"Shenzhen KTC Technology Group","SKG"},
 {"Truly Semiconductors Ltd.","TLY"},
 {"Hitevision Group","HHT"},
 {"DLOGIC Ltd.","DLM"},
 {"Fun Technology Innovation INC.","FUL"},
 {"Guangxi Century Innovation Display Electronics Co., Ltd","IOC"},
 {"ICC Intelligent Platforms GmbH","EMR"},
 {"New H3C Technology Co., Ltd.","NHC"},
 {"Seco S.p.A.","SCG"},
 {"Silent Power Electronics GmbH","LCP"},
 {"NAFASAE INDIA Pvt. Ltd","NAF"},
 {"Pico Technology Inc.","PIR"},
 {"Life is Style Inc.","LIS"},
 {"Hansung Co., Ltd","HSN"},
 {"Hubei Century Joint Innovation Technology Co.Ltd","TTR"},
 {"Zake IP Holdings LLC (3B tech)","VIO"},
 {"PreSonus Audio Electronics","PAE"},
 {"C&amp;T Solution Inc.","MXM"},
 {"VARCem","VCE"},
 {"Nextorage Corporation","NXR"},
 {"Netvio Ltd.","NVO"},
 {"Beijing Guochengwantong Information Technology Co., Ltd.","STV"},
